server_url: <%= ENV['ELASTIC_APM_SERVER_URL'] %>
secret_token: <%= ENV['ELASTIC_APM_SECRET_TOKEN'] %>
server_ca_cert_file: <%= ENV['ELASTIC_APM_SERVER_CA_CERT_FILE'] %>
service_name: 'analyst-console-escalations'
disable_metrics: ["*"]