development:
  amq: #active message queue
    host: "localhost"
    timeout: 2
  api_timeout:
    timeout: 15
  auto_resolve:
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      api_key: "redacted"
  bls:
    host: "stage-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "fmd-bugzil-01tst.vrt.sourcefire.com"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "ava-esqulb-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: ""
    password: ""
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  peakebridge:
    host: "localhost"
    port: 2966
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    #ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_s3_host_name: "US East (N. Virginia)"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  perl:
    cmd: "/usr/bin/env perl"
    canvas_root: "extras"
    extras_dir: 'extras'
    visruleparser_path: "extras/visruleparser.pl"
    snort_json_path: 'extras/snort_json_parser.pl'
    cve2x_path: "extras/cve2x.pl"
    rule2yaml_path: "extras/rule2yaml.pl"
  rep_api:
    host: "fmdreputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    username: "u/sourcefire"
    password: "redacted"
  ruletest:
    url: "https://localhost:3000/api_test"
  sds:
    host: "v2.sds.cisco.com"
    cert_file: "/usr/local/etc/sds-certificate.pem"
    pkey_file: "/usr/local/etc/sds-pkey.pem"
  snort_doc_max_fails: 3
  snort_org:
    host: "localhost"
    port: 3000
    api_key: "redacted"
  svn:
    cmd: "/usr/bin/env svn"
    password: ""
    rules_repo_url: "https://repo-test.vrt.sourcefire.com/svn/rules/trunk"
    ruledocs_repo_url: "https://repo-test.vrt.sourcefire.com/svn/rules/trunk/docs/rulesdocs/"
    snort_rule_path: "extras/snort/snort-rules"
  talos_intelligence:
    host: "localhost"
    port: 3000
    verify_mode: "no-tls"
    api_key: "redacted"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    verify_mode: "verify-none"
    api_key: "redacted"
  ticloud:
    host: "ticloud-cdn-api.reversinglabs.com"
    port: 443
    verify_mode: "verify-none"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    api_key: "redacted"
  wbrs:
    host: "test-wbrsruleapi-app1.vega.ironport.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    gssnegotiate: false
    auth_token: "redacted"
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false

test:
  amq: #active message queue
    host: "localhost"
    timeout: 2
  api_timeout:
    timeout: 15
  auto_resolve:
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      api_key: "redacted"
  bls:
    host: "stage-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "fmd-bugzil-01tst.vrt.sourcefire.com"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "ava-esqulb-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: ""
    password: ""
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    verify_mode: "verify-none"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  peakebridge:
    host: "localhost"
    port: 2966
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_s3_host_name: "US East (N. Virginia)"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  perl:
    cmd: "/usr/bin/env perl"
    canvas_root: "extras"
    extras_dir: 'extras'
    visruleparser_path: "extras/visruleparser_dev.pl"
    snort_json_path: 'extras/snort_json_parser.pl'
    cve2x_path: "extras/cve2x_dev.pl"
    rule2yaml_path: "extras/rule2yaml_dev.pl"
  rep_api:
    #host: "localhost"
    #port: 2944                          #default port for wbrs_stub
    #verify_mode: "no-tls"
    #gssnegotiate: true
    host: "fmdreputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    gssnegotiate: true
  reversing_labs:
    url: "https://ticloud-cdn-api.reversinglabs.com/"
    username: "u/sourcefire"
    password: "redacted"
  ruletest:
    url: "https://localhost:3000/api_test"
  sds:
    host: "v2.sds.cisco.com"
    ca_cert_file: "/usr/local/etc/sds-certificate.pem"
    pkey_file: "/usr/local/etc/sds-pkey.pem"
    username: 'REDACTED'
    password: "REDACTED"
  snort_doc_max_fails: 1
  snort_org:
    host: "localhost"
    port: 3000
    api_key: "redacted"
  svn:
    cmd: "/usr/bin/env svn"
    password: "redacted"
    rules_repo_url: "https://repo-test.vrt.sourcefire.com/svn/rules/trunk"
    ruledocs_repo_url: "https://repo-test.vrt.sourcefire.com/svn/rules/trunk/docs/rulesdocs/"
    snort_rule_path: "extras/snort/snort-rules"
  talos_intelligence:
    host: "localhost"
    port: 3000
    verify_mode: "no-tls"
    api_key: "redacted"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    verify_mode: "verify-none"
    api_key: "redacted"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    api_key: "redacted"
  wbrs:
    host: "test-wbrsruleapi-app1.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false
    auth_token: "redacted"
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false

staging:
  amq:
    host: "fmd-actmq-01stg.vrt.sourcefire.com"
    timeout: 2
  api_timeout:
    timeout: 15
  auto_resolve:
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      api_key: "redacted"
  bls:
    host: "stage-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "fmd-bugzil-01stg.vrt.sourcefire.com"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "ava-esqulb-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: ""
    password: ""
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    api_key: "redacted"
  peakebridge:
    host: "stevensville-stage.vrt.sourcefire.com"
    port: 443
    ssl_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_s3_host_name: "US East (N. Virginia)"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  perl:
    cmd: "/usr/local/bin/perl"
    canvas_root: "extras"
    extras_dir: 'extras'
    visruleparser_path: "extras/visruleparser.pl"
    snort_json_path: 'extras/snort_json_parser.pl'
    cve2x_path: "extras/cve2x.pl"
    rule2yaml_path: "extras/rule2yaml.pl"
  rep_api:
    host: "fmdreputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    username: "u/sourcefire"
    password: "redacted"
  ruletest:
    url: "https://ruletest-staging.vrt.sourcefire.com"
  sds:
    host: "v2.sds.cisco.com"
    cert_file: "/usr/local/etc/sds-certificate.pem"
    pkey_file: "/usr/local/etc/sds-pkey.pem"
    user: 'tidev'
    pass: "redacted"
  snort_doc_max_fails: 3
  snort_org:
    host: "localhost"
    port: 3000
    api_key: "redacted"
  svn:
    cmd: "/usr/local/bin/svn"
    password: ""
    rules_repo_url: "https://repo-staging.vrt.sourcefire.com/svn/rules/trunk"
    ruledocs_repo_url: "https://repo-staging.vrt.sourcefire.com/svn/rules/trunk/docs/ruledocs/"
    snort_rule_path: "extras/snort/snort-rules"
  talos_intelligence:
    host: "localhost"
    port: 3000
    verify_mode: "no-tls"
    api_key: "redacted"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    api_key: "redacted"
  ticloud:
    host: "ticloud-cdn-api.reversinglabs.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    api_key: "redacted"
  wbrs:
    host: "stage-wbrsruleapi-vip.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false
    auth_token: "redacted"
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false

production:
  amq: #active message queue
    host: "mq.vrt.sourcefire.com"
    timeout: 2
  api_timeout:
    timeout: 15
  auto_resolve:
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      api_key: "redacted"
  bugzilla:
    host: "bugzilla.vrt.sourcefire.com"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "ava-esqulb-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: ""
    password: ""
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  peakebridge:
    host: "stevensville.vrt.sourcefire.com"
    port: 443
    ssl_mode: "verify-peer"
    ca_file: "/usr/local/etc/trusted-certificates.pem"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  perl:
    cmd: "/usr/local/bin/perl"
    canvas_root: "extras"
    extras_dir: 'extras'
    visruleparser_path: "extras/visruleparser.pl"
    snort_json_path: 'extras/snort_json_parser.pl'
    cve2x_path: "extras/cve2x.pl"
    rule2yaml_path: "extras/rule2yaml.pl"
  rep_api:
    host: "reputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    username: "u/sourcefire"
    password: "redacted"
  ruletest:
    url: "https://ruletest.vrt.sourcefire.com"
  sds:
    host: "v2.sds.cisco.com"
    cert_file: "/usr/local/etc/sds-certificate.pem"
    pkey_file: "/usr/local/etc/sds-pkey.pem"
  snort_doc_max_fails: 10
  snort_org:
    host: "snort.org"
    port: 443
    api_key: "redacted"
  svn:
    cmd: "/usr/local/bin/svn"
    password: ""
    rules_repo_url: "https://repo.vrt.sourcefire.com/svn/rules/trunk"
    ruledocs_repo_url: "https://repo.vrt.sourcefire.com/svn/rules/trunk/docs/ruledocs/"
    snort_rule_path: "extras/snort/snort-rules"
  talos_intelligence:
    host: "localhost"
    port: 3000
    verify_mode: "no-tls"
    api_key: "redacted"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    api_key: "redacted"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    api_key: "redacted"
  wbrs:
    host: "prod-wbrsruleapi-vip.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: false
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false

