development:
  api_timeout:
    timeout: 15
  app_info:
    client_cert_file: "/usr/local/etc/talos/tess-client.pem"
    pkey_file: "/usr/local/etc/talos/tess-pkey.pem"
    # device_id: "analyst-console-escalations-dev"   # defaults to hostname
    # product_family: "Talos_Web"
    # product_id: "analyst-console-escalations"
    # product_version: 'development'    # defaults to git branch name or Rails.env
  auto_resolve:
    check_matching_disposition: true
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      api_key: "redacted"
  beaker:
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    hostport: "annapolis-stage.vrt.sourcefire.com:4252"
  bls:
    host: "stage-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "fmd-bugzil-01tst.vrt.sourcefire.com"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "ava-esqulb-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: ""
    password: ""
  file_mgmt:
    base_host_path: "/tmp/"
    base_file_path: "analyst_console/escalations/"
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  guard_rails:
    host: "fmd-guard-01tst.vrt.sourcefire.com"
    #host: "10.7.30.135"
    port: 443
    verify_mode: "verify-none"
    tls_mode: "verify-none"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  magic_api:
    host: "magic.vrt.sourcefire.com"
    port: 80
  peakebridge:
    host: "localhost"
    port: 2966
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_s3_host_name: "US East (N. Virginia)"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  rep_api:
    host: "fmdreputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    url: "https://ticloud-cdn-api.reversinglabs.com/"
    username: "u/sourcefire"
    password: "redacted"
  sds:
    #host: "v2.sds.cisco.com"
    host: "v3-cat2020.sds.cisco.com"
    ca_cert_file: "/usr/local/etc/sds-certificate.pem"
    cert_file: "/usr/local/etc/talos/talos-web-certificate.pem"
    pkey_file: "/usr/local/etc/talos/talos-web-pkey.pem"
    user: "tidev"
    pass: "redacted"
  sds_v3:
    host: "v3.sds.cisco.com"
    cert_file: "/usr/local/etc/talos/talos-web-certificate.pem"
    pkey_file: "/usr/local/etc/talos/talos-web-pkey.pem"
    user: "tidev"
    pass: "redacted"
  tess:
    host: "tess.sl.talos.cisco.com"
    port: 443
    ca_cert_file: "/usr/local/etc/talos/tess-ca-cert.pem"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    verify_mode: "verify-none"
    gssnegotiate: false
    api_key: "redacted"
  ticloud:
    host: "ticloud-cdn-api.reversinglabs.com"
    port: 443
    verify_mode: "verify-none"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    api_key: "redacted"
  wbrs:
    driver: "http"
    host: "test-wbrsruleapi-app1.vega.ironport.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    gssnegotiate: false
    auth_token: "redacted"
  k2:
    host: "k2-api-int.sv4.ironport.com"
    port: 443
    token: "redacted"
  enrichment_service:
    hostport: "grpc.talos.cisco.com:443"
    cert_file: "/usr/local/etc/talos/tess-client.pem"
    key_file: "/usr/local/etc/talos/tess-pkey.key"
  umbrella_data_fetcher:
    aws:
      access_key_id: "redacted"
      secret_access_key: "redacted"
  jira:
    host: "https://fmd-drgjr-01tst.vrt.sourcefire.com:443/"
    token: "redacted"
    verify_mode: "verify-none"
    auth_type: "basic"
    project_key: "SDOCS"
  bast:
    host: "prod-webcat-app3.sv4.ironport.com"
    port: 5000
    api_key: "redacted"
    tls: "verify-none"  

test:
  api_timeout:
    timeout: 15
  app_info:
    client_cert_file: "/usr/local/etc/talos/tess-client.pem"
    pkey_file: "/usr/local/etc/talos/tess-pkey.pem"
    # device_id: "analyst-console-escalations-dev" #use dev for test environment to the TESS server it is dev
    # product_family: "Talos_Web"
    # product_id: "analyst-console-escalations"
    # product_version: 'test'    # defaults to git branch name or Rails.env
  auto_resolve:
    check_matching_disposition: true
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      api_key: "redacted"
  beaker:
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    hostport: "annapolis-stage.vrt.sourcefire.com:4252"
  bls:
    host: "stage-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "fmd-bugzil-01tst.vrt.sourcefire.com"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "ava-esqulb-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: ""
    password: ""
  file_mgmt:
    base_host_path: "/tmp/"
    base_file_path: "analyst_console/escalations/"
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  guard_rails:
    host: "fmd-guard-01tst.vrt.sourcefire.com"
    #host: "10.7.30.135"
    port: 443
    verify_mode: "verify-none"
    tls_mode: "verify-none"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  magic_api:
    host: "magic.vrt.sourcefire.com"
    port: 80
  peakebridge:
    host: "localhost"
    port: 2966
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_s3_host_name: "US East (N. Virginia)"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  rep_api:
    host: "fmdreputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    url: "https://ticloud-cdn-api.reversinglabs.com/"
    username: "u/sourcefire"
    password: "redacted"
  sds:
    host: "v2.sds.cisco.com"
    ca_cert_file: "/usr/local/etc/sds-certificate.pem"
    cert_file: "/usr/local/etc/talos/talos-web-certificate.pem"
    pkey_file: "/usr/local/etc/talos/talos-web-pkey.pem"
    user: "tidev"
    pass: "redacted"
  sds_v3:
    host: "v3.sds.cisco.com"
    cert_file: "/usr/local/etc/talos/talos-web-certificate.pem"
    pkey_file: "/usr/local/etc/talos/talos-web-pkey.pem"
    user: "tidev"
    pass: "redacted"
  tess:
    host: "tess.sl.talos.cisco.com"
    port: 443
    ca_cert_file: "/usr/local/etc/talos/tess-ca-cert.pem"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    verify_mode: "verify-none"
    gssnegotiate: false
    api_key: "redacted"
  ticloud:
    host: "ticloud-cdn-api.reversinglabs.com"
    port: 443
    verify_mode: "verify-none"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    verify_mode: "verify-none"
    api_key: "redacted"
  wbrs:
    driver: "http"
    host: "test-wbrsruleapi-app1.vega.ironport.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    gssnegotiate: false
    auth_token: "redacted"
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false
  k2:
    host: "k2-api-int.sv4.ironport.com"
    port: 443
    token: "redacted"
  umbrella_data_fetcher:
    aws:
      access_key_id: "redacted"
      secret_access_key: "redacted"
  jira:
    host: "https://fmd-drgjr-01tst.vrt.sourcefire.com:443/"
    token: "redacted"
    verify_mode: "verify-none"
    auth_type: "basic"
    project_key: "SD"
staging:
  amp_poke:
    host: "localhost"
    #host: "poke.vrt.sourcefire.com"
    verify_mode: "verify-none"
  api_timeout:
    timeout: 15
  app_info:
    client_cert_file: "/usr/local/etc/talos/tess-client.pem"
    pkey_file: "/usr/local/etc/talos/tess-pkey.pem"
    # device_id defaults to hostname
    # product_family: "Talos_Web"
    # product_id: "analyst-console-escalations"
    # product_version: defaults to version file or Rails.env
  auto_resolve:
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      # umbrella always uses https and verify peer
      api_key: "redacted"
  beaker:
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    hostport: "annapolis-stage.vrt.sourcefire.com:4252"
  bls:
    host: "stage-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "fmd-bugzil-01stg.vrt.sourcefire.com"
    login: "talosweb@cisco.com"
    password: "redacted"
    api_key: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "moaec-query.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: "redacted"
    password: "redacted"
  file_mgmt:
    base_host_path: "/nfs/fmd_bugz_s3c/"
    base_file_path: "analyst_console/escalations/"
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  guard_rails:
    host: "fmd-guard-01tst.vrt.sourcefire.com"
    #host: "10.7.30.135"
    port: 443
    verify_mode: "verify-none"
    tls_mode: "verify-none"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  magic_api:
    host: "magic.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
  peakebridge:
    host: "stevensville-stage.vrt.sourcefire.com"
    port: 443
    ssl_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_s3_host_name: "US East (N. Virginia)"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  rep_api:
    host: "fmdreputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-none"
    username: "u/sourcefire"
    password: "redacted"
  sds:
    category_version: "v10"
    # Old host name -> host: "v2.beta.sds.cisco.com"
    #host: "v3-cat2020.sds.cisco.com"
    host: "v2.beta.sds.cisco.com"
    ca_cert_file: "/usr/local/etc/analyst-console-escalations/talos-web-certificate.pem"
    pkey_file: "/usr/local/etc/analyst-console-escalations/talos-web-pkey.pem"
    v3_host: "v3-web-intel-rest-integration.talos.cisco.com"
    username: "redacted"
    password: "redacted"
  tess:
    host: "tess.sl.talos.cisco.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/analyst-console-escalations/tess-ca_cert.pem"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    gssnegotiate: false
    api_key: "redacted"
  ticloud:
    host: "ticloud-cdn-api.reversinglabs.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    api_key: "redacted"
  wbrs:
    auth_token: "redacted"
    host: "test-wbrsruleapi-app1.vega.ironport.com"
    port: 80 
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    consumer_key: "TEST"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false
  k2:
    host: "k2-api-int.sv4.ironport.com"
    port: 443
    token: "redacted"
  umbrella_data_fetcher:
    aws:
      access_key_id: "redacted"
      secret_access_key: "redacted"
  jira:
    host: "fmd-drgjr-01tst.vrt.sourcefire.com"
    username: "TBD.gen"
    password: "redacted"
    verify_mode: "verify-none"
production:
  amp_poke: 
    host: "poke.vrt.sourcefire.com"
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
  api_timeout:
    timeout: 15
  app_info:
    client_cert_file: "/usr/local/etc/talos/tess-client.pem"
    pkey_file: "/usr/local/etc/talos/tess-pkey.pem"
    # device_id defaults to hostname
    # product_family: "Talos_Web"
    # product_id: "analyst-console-escalations"
    # product_version: defaults to version file or Rails.env
  auto_resolve:
    complaints:
      check: true
    virus_total:
      check: true
    umbrella:
      check: true
      url: "https://investigate.api.umbrella.com/domains/categorization/"
      # umbrella always uses https and verify peer
      api_key: "redacted"
  beaker:
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    hostport: "annapolis.vrt.sourcefire.com:4252"
  bls:
    host: "prod-bls-vip.sv4.ironport.com"
    port: 443
  bugzilla:
    host: "bugzilla.vrt.sourcefire.com"
    login: "redacted"
    password: "redacted"
  cert:
    vrt: "/usr/local/etc/trusted-certificates.pem"
  elastic:
    host: "moaec-query.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    username: "redacted"
    password: "redacted"
  file_mgmt:
    base_host_path: "/nfs/fmd_bugz_s3c/"
    base_file_path: "analyst_console/escalations/"
  file_reputation_sandbox:
    host: "intel.api.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    api_keys:
      AC-Form: "redacted"
      TI-Form: "redacted"
      TI-API: "redacted"
  guard_rails:
    host: "ava-guard-01prd.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-none"
    tls_mode: "verify-none"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  magic_api:
    host: "magic.vrt.sourcefire.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
  peakebridge:
    host: "stevensville.vrt.sourcefire.com"
    port: 443
    ssl_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    uri_base: "/peakebridge/channels"
    sources:
      "snort-org":
        aws_access_key_id: "redacted"
        aws_secret_access_key: "redacted"
        aws_region: "us-east-1"
        aws_bucket: "redacted"
  rep_api:
    host: "reputation.vrt.sourcefire.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: true
  reversing_labs:
    host: 'ticloud-cdn-api.reversinglabs.com'
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    username: "u/sourcefire"
    password: "redacted"
    url: "https://ticloud-cdn-api.reversinglabs.com/"
  sds:
    host: "v2.sds.cisco.com"
    v3_host: "v3-web-intel-rest.talos.cisco.com"
    ca_cert_file: "/usr/local/etc/analyst-console-escalations/sds-certificate.pem"
    category_version: "v10"
    pkey_file: "/usr/local/etc/analyst-console-escalations/talos-web-pkey.pem"
    user: "talosintel" 
    pass: "redacted"
  tess:
    host: "tess.sl.talos.cisco.com"
    port: 443
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/analyst-console-escalations/tess-ca_cert.pem"
  threatgrid:
    host: "panacea.threatgrid.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    gssnegotiate: false
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    api_key: "redacted"
  ticloud:
    host: "ticloud-cdn-api.reversinglabs.com"
    port: 443
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "verify-peer"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
  virustotal:
    url: "https://www.virustotal.com/vtapi/v2/url/report"
    host: "www.virustotal.com"
    port: 443
    # virustotal always uses https and verify peer
    api_key: "redacted"
  wbrs:
    auth_token: "redacted"
    host: "prod-wbrsruleapi-vip.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    ca_cert_file: "/usr/local/etc/trusted-certificates.pem"
    gssnegotiate: false
  xbrs:
    host: "prod-xbrs.vega.ironport.com"
    port: 80
    # verify_mode { "no-tls" for http, "verify-none" for self signed cert, "verify-peer" for CA }
    verify_mode: "no-tls"
    gssnegotiate: false
  k2:
    host: "k2-api.sv4.ironport.com"
    port: 443
    token: "redacted"
  umbrella_data_fetcher:
    aws:
      access_key_id: "redacted"
      secret_access_key: "redacted"
  jira:
    host: "fmd-drgjr-01tst.vrt.sourcefire.com"
    username: "TBD.gen"
    password: "redacted"
    verify_mode: "verify-none"
