# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8980f771352ffcd781ee297817a89783d20b3a3ab6ed8c92e0ab4a2913e709b0ab373d1c6a614db8115c3f23d125c3abaac19bfe0da41503ac0666fecf222deb

test:
  secret_key_base: 0152166a7dc3e2c88566e087d692674e01d8b40fcacb995ea6ce4b14c039078d084fb2fa89aa1e2f357531b922c062d0a03e9d14f6a6715ac47ed3314151e984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
