# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b1ea0ad23090e811c0172ceb4c509ccbb5c46ec61b46f71fe4756615be45fb9eb32cd80f67a7b6503a8b876737018af68980edf35e8e596ad571bde6da5f71

test:
  secret_key_base: 453484e8a75a5ea97be2dea54a5e0fb7c3e887f542257851e945a0746bd86a1cba10839b8861a51f0af035450efb5f3d84326e10ce78a042fc4a02b49a967edc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
