# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection-status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("connection-status.proto", :syntax => :proto3) do
    add_message "Talos.ConnectionStatus.Request" do
    end
    add_message "Talos.ConnectionStatus.EndpointStatus" do
      optional :base_url, :string, 1
      optional :is_connected, :bool, 2
      optional :last_error, :string, 3
    end
    add_message "Talos.ConnectionStatus.ServiceStatus" do
      optional :name, :string, 1
      repeated :endpoint_status, :message, 2, "Talos.ConnectionStatus.EndpointStatus"
    end
    add_message "Talos.ConnectionStatus.Reply" do
      repeated :services, :message, 2, "Talos.ConnectionStatus.ServiceStatus"
    end
  end
end

module Talos
  module ConnectionStatus
    Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ConnectionStatus.Request").msgclass
    EndpointStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ConnectionStatus.EndpointStatus").msgclass
    ServiceStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ConnectionStatus.ServiceStatus").msgclass
    Reply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ConnectionStatus.Reply").msgclass
  end
end
