# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enrichment_service.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("enrichment_service.proto", :syntax => :proto3) do
    add_message "Talos.ENRICH.QueryDomainRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :domain, :string, 2
    end
    add_message "Talos.ENRICH.QueryURLRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :url, :message, 2, "Talos.URL"
    end
    add_message "Talos.ENRICH.QueryIPRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :ip, :message, 2, "Talos.IPAddress"
    end
    add_message "Talos.ENRICH.QuerySHARequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :sha, :string, 2
    end
    add_message "Talos.ENRICH.QueryReply" do
      optional :taxonomy_map_version, :uint32, 1
      repeated :context_tags, :message, 2, "Talos.ContextTag"
      repeated :context_tag_groups, :message, 3, "Talos.ContextGroup"
      repeated :web_context_tags, :message, 4, "Talos.ContextTag"
      repeated :web_context_tag_groups, :message, 5, "Talos.ContextGroup"
      repeated :email_context_tags, :message, 6, "Talos.ContextTag"
      repeated :email_context_tag_groups, :message, 7, "Talos.ContextGroup"
    end
    add_message "Talos.ENRICH.PrivateLog" do
      optional :reply, :message, 5, "Talos.ENRICH.QueryReply"
      optional :client, :message, 6, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 7
      optional :response_sent_ts, :uint64, 8
      optional :grpc_status_code, :uint32, 9
      oneof :request do
        optional :domain, :message, 1, "Talos.ENRICH.QueryDomainRequest"
        optional :url, :message, 2, "Talos.ENRICH.QueryURLRequest"
        optional :ip, :message, 3, "Talos.ENRICH.QueryIPRequest"
        optional :sha, :message, 4, "Talos.ENRICH.QuerySHARequest"
      end
    end
  end
end

module Talos
  module ENRICH
    QueryDomainRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryDomainRequest").msgclass
    QueryURLRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryURLRequest").msgclass
    QueryIPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryIPRequest").msgclass
    QuerySHARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QuerySHARequest").msgclass
    QueryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryReply").msgclass
    PrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.PrivateLog").msgclass
  end
end
