# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enrich.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("enrich.proto", :syntax => :proto3) do
    add_message "Talos.ENRICH.QueryDomainRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :domain, :string, 2
      map :taxonomy_versions, :uint32, :uint32, 3
    end
    add_message "Talos.ENRICH.QueryURLRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :url, :message, 2, "Talos.URL"
      map :taxonomy_versions, :uint32, :uint32, 3
    end
    add_message "Talos.ENRICH.QueryIPRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :ip, :message, 2, "Talos.IPAddress"
      map :taxonomy_versions, :uint32, :uint32, 3
    end
    add_message "Talos.ENRICH.QuerySHARequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :sha, :string, 2
      map :taxonomy_versions, :uint32, :uint32, 3
    end
    add_message "Talos.ENRICH.QueryReply" do
      optional :taxonomy_map_version, :uint32, 1
      repeated :context_tags, :message, 2, "Talos.ContextTag"
      repeated :context_tag_groups, :message, 3, "Talos.ContextGroup"
      repeated :web_context_tags, :message, 4, "Talos.ContextTag"
      repeated :web_context_tag_groups, :message, 5, "Talos.ContextGroup"
      repeated :email_context_tags, :message, 6, "Talos.ContextTag"
      repeated :email_context_tag_groups, :message, 7, "Talos.ContextGroup"
    end
    add_message "Talos.ENRICH.PrivateLog" do
      optional :reply, :message, 5, "Talos.ENRICH.QueryReply"
      optional :client, :message, 6, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 7
      optional :response_sent_ts, :uint64, 8
      optional :grpc_status_code, :uint32, 9
      oneof :request do
        optional :domain, :message, 1, "Talos.ENRICH.QueryDomainRequest"
        optional :url, :message, 2, "Talos.ENRICH.QueryURLRequest"
        optional :ip, :message, 3, "Talos.ENRICH.QueryIPRequest"
        optional :sha, :message, 4, "Talos.ENRICH.QuerySHARequest"
      end
    end
    add_message "Talos.ENRICH.STIXPrivateLog" do
      optional :reply, :message, 5, "Talos.ENRICH.STIXReply"
      optional :client, :message, 6, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 7
      optional :response_sent_ts, :uint64, 8
      optional :grpc_status_code, :uint32, 9
      oneof :request do
        optional :domain, :message, 1, "Talos.ENRICH.QueryDomainRequest"
        optional :url, :message, 2, "Talos.ENRICH.QueryURLRequest"
        optional :ip, :message, 3, "Talos.ENRICH.QueryIPRequest"
        optional :sha, :message, 4, "Talos.ENRICH.QuerySHARequest"
      end
    end
    add_message "Talos.ENRICH.HashPrevalenceRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      repeated :hash_string, :string, 2
      optional :hash_type, :string, 3
      optional :index_type, :string, 4
      optional :first_seen, :string, 5
      optional :last_seen, :string, 6
    end
    add_message "Talos.ENRICH.PrevalenceDisposition" do
      optional :count, :int64, 1
      optional :first_seen, :string, 2
      optional :last_seen, :string, 3
    end
    add_message "Talos.ENRICH.PrevalenceHashDataset" do
      optional :count, :int64, 1
      map :dispositions, :string, :message, 2, "Talos.ENRICH.PrevalenceDisposition"
    end
    add_message "Talos.ENRICH.PrevalenceDataset" do
      optional :count, :int64, 1
      optional :first_seen, :string, 2
      optional :last_seen, :string, 3
    end
    add_message "Talos.ENRICH.HashPrevalenceResponse" do
      optional :count, :int64, 1
      map :datasets, :string, :message, 2, "Talos.ENRICH.PrevalenceHashDataset"
      repeated :dispositions, :string, 3
      optional :hash_type, :string, 4
      optional :first_seen, :string, 5
      optional :last_seen, :string, 6
      optional :took, :int32, 7
    end
    add_message "Talos.ENRICH.HashPrevalenceResponseSet" do
      map :responses, :string, :message, 1, "Talos.ENRICH.HashPrevalenceResponse"
    end
    add_message "Talos.ENRICH.DomainPrevalenceRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :index_type, :string, 2
      repeated :domain, :string, 3
      optional :first_seen, :string, 6
      optional :last_seen, :string, 7
    end
    add_message "Talos.ENRICH.DomainPrevalenceResponse" do
      optional :count, :int64, 1
      map :datasets, :string, :message, 2, "Talos.ENRICH.PrevalenceDataset"
      optional :first_seen, :string, 3
      optional :last_seen, :string, 4
    end
    add_message "Talos.ENRICH.DomainPrevalenceResponseSet" do
      map :responses, :string, :message, 1, "Talos.ENRICH.DomainPrevalenceResponse"
    end
    add_message "Talos.ENRICH.IPPrevalenceRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :index_type, :string, 2
      repeated :ipaddress, :string, 3
      optional :first_seen, :string, 4
      optional :last_seen, :string, 5
    end
    add_message "Talos.ENRICH.IPPrevalenceResponse" do
      optional :count, :int64, 1
      map :datasets, :string, :message, 2, "Talos.ENRICH.PrevalenceDataset"
      optional :first_seen, :string, 3
      optional :last_seen, :string, 4
    end
    add_message "Talos.ENRICH.IPPrevalenceResponseSet" do
      map :responses, :string, :message, 1, "Talos.ENRICH.IPPrevalenceResponse"
    end
    add_message "Talos.ENRICH.PrevalencePrivateLog" do
      optional :client, :message, 7, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 8
      optional :response_sent_ts, :uint64, 9
      optional :grpc_status_code, :uint32, 10
      oneof :request do
        optional :req_hash, :message, 1, "Talos.ENRICH.HashPrevalenceRequest"
        optional :req_domain, :message, 2, "Talos.ENRICH.DomainPrevalenceRequest"
        optional :req_ip, :message, 3, "Talos.ENRICH.IPPrevalenceRequest"
      end
      oneof :response do
        optional :res_hash, :message, 4, "Talos.ENRICH.HashPrevalenceResponseSet"
        optional :res_domain, :message, 5, "Talos.ENRICH.DomainPrevalenceResponseSet"
        optional :res_ip, :message, 6, "Talos.ENRICH.IPPrevalenceResponseSet"
      end
    end
    add_message "Talos.ENRICH.STIXReply" do
      optional :json, :string, 1
    end
  end
end

module Talos
  module ENRICH
    QueryDomainRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryDomainRequest").msgclass
    QueryURLRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryURLRequest").msgclass
    QueryIPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryIPRequest").msgclass
    QuerySHARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QuerySHARequest").msgclass
    QueryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.QueryReply").msgclass
    PrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.PrivateLog").msgclass
    STIXPrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.STIXPrivateLog").msgclass
    HashPrevalenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.HashPrevalenceRequest").msgclass
    PrevalenceDisposition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.PrevalenceDisposition").msgclass
    PrevalenceHashDataset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.PrevalenceHashDataset").msgclass
    PrevalenceDataset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.PrevalenceDataset").msgclass
    HashPrevalenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.HashPrevalenceResponse").msgclass
    HashPrevalenceResponseSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.HashPrevalenceResponseSet").msgclass
    DomainPrevalenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.DomainPrevalenceRequest").msgclass
    DomainPrevalenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.DomainPrevalenceResponse").msgclass
    DomainPrevalenceResponseSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.DomainPrevalenceResponseSet").msgclass
    IPPrevalenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.IPPrevalenceRequest").msgclass
    IPPrevalenceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.IPPrevalenceResponse").msgclass
    IPPrevalenceResponseSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.IPPrevalenceResponseSet").msgclass
    PrevalencePrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.PrevalencePrivateLog").msgclass
    STIXReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.ENRICH.STIXReply").msgclass
  end
end
