# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipd.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ipd.proto", :syntax => :proto3) do
    add_message "Talos.IPD.ReputationRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      repeated :endpoint, :message, 2, "Talos.IPEndpoint"
      optional :connection, :message, 3, "Talos.IPConnection"
    end
    add_message "Talos.IPD.ReputationReply" do
      optional :connection_guid, :bytes, 1
      repeated :result, :message, 2, "Talos.IPD.IPResult"
      optional :rule_map_version, :uint32, 3
      optional :threat_cat_map_version, :uint32, 4
      optional :threat_level_version, :uint32, 5
    end
    add_message "Talos.IPD.IPResult" do
      optional :reputation_x10, :sint32, 1
      optional :no_score, :bool, 2
      optional :threat_level_id, :uint32, 3
      repeated :rep_rule_id, :uint32, 4
      repeated :threat_cat_id, :uint32, 5
      optional :spam_prob_x10000, :uint32, 6
      optional :geo_location, :message, 7, "Talos.GeoLocation"
      optional :geo_coords, :message, 8, "Talos.GeoCoords"
      optional :rvs_rate, :double, 9
      optional :no_rvs_rate, :bool, 10
      optional :network_info, :message, 11, "Talos.IPD.NetInfo"
      optional :org_stats, :message, 12, "Talos.IPD.OrgStats"
      optional :hostname, :string, 13
      optional :domain_magnitude, :message, 14, "Talos.IPD.MagnitudeInfo"
      optional :ipd_error, :enum, 15, "Talos.IPD.IPResult.IPDError"
      optional :error_is_temporary, :bool, 16
    end
    add_enum "Talos.IPD.IPResult.IPDError" do
      value :IPDERROR_NONE, 0
      value :IPDERROR_UNKNOWN, 1
      value :IPDERROR_INPUT, 2
      value :IPDERROR_CACHE_DECODE, 3
      value :IPDERROR_CACHE, 4
      value :IPDERROR_CACHE_NOT_INITIALIZED, 5
      value :IPDERROR_RULE_MAP, 6
    end
    add_message "Talos.IPD.MagnitudeInfo" do
      optional :daily_x10, :uint32, 1
      optional :monthly_x10, :uint32, 2
    end
    add_message "Talos.IPD.OrgInfo" do
      optional :org_name, :string, 1
      optional :org_id, :uint32, 2
    end
    add_message "Talos.IPD.OrgInfoRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :org_info, :message, 2, "Talos.IPD.OrgInfo"
    end
    add_message "Talos.IPD.DomainInfoRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :name, :string, 2
    end
    add_message "Talos.IPD.DomainInfoReply" do
      optional :domain_name, :string, 1
      optional :domain_id, :uint32, 2
      optional :magnitude, :message, 3, "Talos.IPD.MagnitudeInfo"
      optional :first_occurence, :uint64, 4
      optional :org_stats, :message, 5, "Talos.IPD.OrgStats"
    end
    add_message "Talos.IPD.NetInfo" do
      optional :cidr_range, :uint32, 1
      optional :subdivision_mask, :uint32, 2
      optional :magnitude, :message, 3, "Talos.IPD.MagnitudeInfo"
      optional :average_magnitude_x10, :uint32, 4
    end
    add_message "Talos.IPD.OrgStats" do
      optional :org_info, :message, 1, "Talos.IPD.OrgInfo"
      optional :magnitude, :message, 2, "Talos.IPD.MagnitudeInfo"
      optional :first_occurence, :uint64, 3
      optional :num_domains, :uint32, 4
      optional :num_ip_controlled, :uint32, 5
      optional :num_ip_email_senders, :uint32, 6
      optional :volume_forever, :uint64, 7
    end
    add_message "Talos.IPD.RuleMapRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.IPD.ThreatCatMapRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.IPD.ThreatLevelMapRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.IPD.PrivateLog" do
      optional :request, :message, 1, "Talos.IPD.ReputationRequest"
      optional :reply, :message, 2, "Talos.IPD.ReputationReply"
      optional :client, :message, 3, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 4
      optional :response_sent_ts, :uint64, 5
      optional :grpc_status_code, :uint32, 6
    end
  end
end

module Talos
  module IPD
    ReputationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.ReputationRequest").msgclass
    ReputationReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.ReputationReply").msgclass
    IPResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.IPResult").msgclass
    IPResult::IPDError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.IPResult.IPDError").enummodule
    MagnitudeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.MagnitudeInfo").msgclass
    OrgInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.OrgInfo").msgclass
    OrgInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.OrgInfoRequest").msgclass
    DomainInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.DomainInfoRequest").msgclass
    DomainInfoReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.DomainInfoReply").msgclass
    NetInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.NetInfo").msgclass
    OrgStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.OrgStats").msgclass
    RuleMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.RuleMapRequest").msgclass
    ThreatCatMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.ThreatCatMapRequest").msgclass
    ThreatLevelMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.ThreatLevelMapRequest").msgclass
    PrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.IPD.PrivateLog").msgclass
  end
end
