# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log-gen.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("log-gen.proto", :syntax => :proto3) do
    add_message "Talos.Log.GenericLog" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :desc, :string, 2
      optional :data, :bytes, 3
    end
  end
end

module Talos
  module Log
    GenericLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Log.GenericLog").msgclass
  end
end
