# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sb-api.proto for package ''

require 'grpc'
require 'sb-api_pb'

module SBAPI
  # The SB-API service definition
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'SB_API'

    # Sends a whois query
    rpc :WhoIsQuery, ::WhoIsSearchRequest, ::WhoIsSearchResponse
  end

  Stub = Service.rpc_stub_class
end
