# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sb-api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sb-api.proto", :syntax => :proto3) do
    add_message "WhoIsSearchRequest" do
      optional :search_string, :string, 1
    end
    add_message "WhoIsSearchResponse" do
      optional :result, :string, 1
      optional :status, :enum, 2, "WhoIsSearchResponse.WhoIsStatus"
      optional :status_message, :string, 3
    end
    add_enum "WhoIsSearchResponse.WhoIsStatus" do
      value :WHOIS_SUCCESS, 0
      value :WHOIS_WARNING, 1
      value :WHOIS_ERROR, 2
    end
  end
end

WhoIsSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WhoIsSearchRequest").msgclass
WhoIsSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WhoIsSearchResponse").msgclass
WhoIsSearchResponse::WhoIsStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WhoIsSearchResponse.WhoIsStatus").enummodule
