# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdr.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sdr.proto", :syntax => :proto3) do
    add_message "Talos.SDR.EnvelopeRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :endpoint, :message, 2, "Talos.IPEndpoint"
      optional :smtp_envelope, :message, 3, "Talos.SMTPEnvelope"
      optional :connection, :message, 4, "Talos.IPConnection"
      optional :msg_guid, :bytes, 5
    end
    add_message "Talos.SDR.EnvelopeReply" do
      optional :msg_guid, :bytes, 1
      optional :threat_level_id, :uint32, 2
      optional :query_ts, :uint64, 3
      repeated :threat_cat_id, :uint32, 4
      optional :threat_cat_map_version, :uint32, 5
      optional :threat_level_map_version, :uint32, 6
      repeated :suspect_domain, :string, 7
      repeated :service_data, :message, 8, "Talos.ServiceData"
      optional :sender_maturity_timestamp, :uint64, 9
      optional :least_mature_sender, :string, 10
    end
    add_message "Talos.SDR.EnvelopeDNS" do
      repeated :sender_ptr, :string, 1
      repeated :mail_from_spf_rec, :message, 2, "Talos.SDR.DNSResult"
      repeated :helo_spf_rec, :message, 3, "Talos.SDR.DNSResult"
    end
    add_message "Talos.SDR.DataDNS" do
      repeated :dkim, :message, 1, "Talos.SDR.DNSRecTXT"
      repeated :dmarc, :message, 2, "Talos.SDR.DNSRecTXT"
    end
    add_message "Talos.SDR.DNSResult" do
      repeated :spf, :message, 1, "Talos.SDR.DNSRecTXT"
      repeated :mx, :message, 2, "Talos.SDR.DNSRecTXT"
      repeated :a, :message, 3, "Talos.SDR.DNSRecA"
      repeated :aaaa, :message, 4, "Talos.SDR.DNSRecAAAA"
      repeated :ptr_v4, :message, 5, "Talos.SDR.DNSRecPTRV4"
      repeated :ptr_v6, :message, 6, "Talos.SDR.DNSRecPTRV6"
      repeated :dkim, :message, 7, "Talos.SDR.DNSRecTXT"
      repeated :dmarc, :message, 8, "Talos.SDR.DNSRecTXT"
    end
    add_message "Talos.SDR.DNSRecTXT" do
      optional :question, :string, 1
      repeated :answer, :string, 2
    end
    add_message "Talos.SDR.DNSRecA" do
      optional :fqdn, :string, 1
      repeated :ipv4_addr, :fixed32, 2
    end
    add_message "Talos.SDR.DNSRecAAAA" do
      optional :fqdn, :string, 1
      repeated :ipv6_addr, :bytes, 2
    end
    add_message "Talos.SDR.DNSRecPTRV4" do
      optional :ipv4_addr, :fixed32, 1
      repeated :fqdn, :string, 2
    end
    add_message "Talos.SDR.DNSRecPTRV6" do
      optional :ipv6_addr, :bytes, 1
      repeated :fqdn, :string, 2
    end
    add_message "Talos.SDR.DataRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :endpoint, :message, 2, "Talos.IPEndpoint"
      optional :smtp_envelope, :message, 3, "Talos.SMTPEnvelope"
      optional :mail_data, :message, 4, "Talos.MailData"
      optional :esa_mid, :uint64, 5
      optional :connection, :message, 6, "Talos.IPConnection"
      optional :msg_guid, :bytes, 7
    end
    add_message "Talos.SDR.DataReply" do
      optional :msg_guid, :bytes, 1
      optional :threat_level_id, :uint32, 2
      optional :query_ts, :uint64, 3
      repeated :threat_cat_id, :uint32, 4
      optional :threat_cat_map_version, :uint32, 5
      optional :threat_level_map_version, :uint32, 6
      repeated :suspect_domain, :string, 7
      repeated :service_data, :message, 8, "Talos.ServiceData"
      optional :sender_maturity_timestamp, :uint64, 9
      optional :least_mature_sender, :string, 10
    end
    add_message "Talos.SDR.ThreatCatMapRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.SDR.ThreatLevelMapRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.SDR.Request" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :endpoint, :message, 2, "Talos.IPEndpoint"
      optional :smtp_envelope, :message, 3, "Talos.SMTPEnvelope"
      optional :mail_data, :message, 4, "Talos.MailData"
      optional :esa_mid, :uint64, 5
      optional :connection, :message, 6, "Talos.IPConnection"
      optional :msg_guid, :bytes, 7
    end
    add_message "Talos.SDR.Reply" do
      optional :msg_guid, :bytes, 1
      optional :threat_level_id, :uint32, 2
      optional :query_ts, :uint64, 3
      repeated :threat_cat_id, :uint32, 4
      optional :threat_cat_map_version, :uint32, 5
      optional :threat_level_map_version, :uint32, 6
      optional :youngest_domain, :string, 7
      repeated :suspect_domain, :string, 8
      repeated :service_data, :message, 9, "Talos.ServiceData"
    end
    add_message "Talos.SDR.PrivateLogEnvelopeQuery" do
      optional :request, :message, 1, "Talos.SDR.EnvelopeRequest"
      optional :reply, :message, 2, "Talos.SDR.EnvelopeReply"
      optional :client, :message, 3, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 4
      optional :response_sent_ts, :uint64, 5
      optional :grpc_status_code, :uint32, 6
    end
    add_message "Talos.SDR.PrivateLogDataQuery" do
      optional :request, :message, 1, "Talos.SDR.DataRequest"
      optional :reply, :message, 2, "Talos.SDR.DataReply"
      optional :client, :message, 3, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 4
      optional :response_sent_ts, :uint64, 5
      optional :grpc_status_code, :uint32, 6
    end
    add_message "Talos.SDR.PrivateLog" do
      optional :request, :message, 1, "Talos.SDR.Request"
      optional :reply, :message, 2, "Talos.SDR.Reply"
      optional :client, :message, 3, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 4
      optional :response_sent_ts, :uint64, 5
      optional :grpc_status_code, :uint32, 6
    end
  end
end

module Talos
  module SDR
    EnvelopeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.EnvelopeRequest").msgclass
    EnvelopeReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.EnvelopeReply").msgclass
    EnvelopeDNS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.EnvelopeDNS").msgclass
    DataDNS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DataDNS").msgclass
    DNSResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DNSResult").msgclass
    DNSRecTXT = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DNSRecTXT").msgclass
    DNSRecA = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DNSRecA").msgclass
    DNSRecAAAA = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DNSRecAAAA").msgclass
    DNSRecPTRV4 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DNSRecPTRV4").msgclass
    DNSRecPTRV6 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DNSRecPTRV6").msgclass
    DataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DataRequest").msgclass
    DataReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.DataReply").msgclass
    ThreatCatMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.ThreatCatMapRequest").msgclass
    ThreatLevelMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.ThreatLevelMapRequest").msgclass
    Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.Request").msgclass
    Reply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.Reply").msgclass
    PrivateLogEnvelopeQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.PrivateLogEnvelopeQuery").msgclass
    PrivateLogDataQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.PrivateLogDataQuery").msgclass
    PrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.SDR.PrivateLog").msgclass
  end
end
