# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-tts.proto for package 'Talos.Service'
# Original file comments:
#
# Service definition for the Talos Taxonomy Service
#

require 'grpc'
require 'service-tts_pb'

module Talos
  module Service
    module TTS
      #
      # Taxonomies
      #
      # Taxonomy Maps for use in translating context tags into names,
      # descriptions, and other items useful for reporting and policy
      # making, are available via the TTS service.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.TTS'

        # Request a mapping of taxonomy ID to taxonomy. The available taxonomies
        # include mappings of ID to description, etc., for data sources, threat
        # categories, threat types, etc. See the `TaxonomyMapRequest` message in
        # `tts.proto` for details of the request structure, and the `TaxonomyMap`
        # message in `talos.proto` for details of the reply stucture.
        rpc :QueryTaxonomyMap, ::Talos::TTS::TaxonomyMapRequest, ::Talos::TaxonomyMap
      end

      Stub = Service.rpc_stub_class
    end
  end
end
