# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-enrich.proto

require 'google/protobuf'

require 'enrich_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service-enrich.proto", :syntax => :proto3) do
  end
end

module Talos
  module Service
  end
end
