# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-tess-internal.proto

require 'google/protobuf'

require 'tess-internal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service-tess-internal.proto", :syntax => :proto3) do
  end
end

module Talos
  module Internal
    module Service
    end
  end
end
