# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-connection-status.proto

require 'google/protobuf'

require 'connection-status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service-connection-status.proto", :syntax => :proto3) do
  end
end

module Talos
  module Service
  end
end
