# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-guid.proto

require 'google/protobuf'

require 'guid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service-guid.proto", :syntax => :proto3) do
  end
end

module Talos
  module Service
  end
end
