# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-tess.proto

require 'google/protobuf'

require 'tess_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service-tess.proto", :syntax => :proto3) do
  end
end

module Talos
  module Service
  end
end
