# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-log-gen.proto for package 'Talos.Service'

require 'grpc'
require 'service-log-gen_pb'

module Talos
  module Service
    module GenericLog
      #
      # Generic Service Logs
      #
      # Defines a generic way to send back new types of service logs without
      # requiring new endpoints or service definitions.
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.GenericLog'

        # Send the generic service log to the Talos service log receiver.
        rpc :SendLog, ::Talos::Log::GenericLog, ::Talos::EmptyReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
