# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-enrichment_service.proto for package 'Talos.Service'
# Original file comments:
#
# Service definition for Enrichment Service
#

require 'grpc'
require 'service-enrich_pb'

module Talos
  module Service
    module ENRICH
      #
      # Enrichment Service
      #
      # The Enrichment Service has four service definitions, one of each observable
      # type (domain, URL, IP, SHA) and returns all tags associated with that
      # observable, including those from other edge services: Sender IP Reputation
      # (IPD), Sender Domain Reputation (SDR), and URL Reputation Service (URS). The
      # results from these edge services will be stored in either the "web" or
      # "email" context_tags or context_tag_groups ("web" from URS and "email" from
      # IPD or SDR). The context from the Enrichment Service is populated into the
      # context_tags and context_tag_groups. Also note that these methods only
      # accept a single observable at a time. There is no batch interface. This
      # service is NOT intended for inline blocking of events. This service IS
      # intended for attribution of why an observable was blocked by one of the
      # other Talos edge services mentioned above.
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.ENRICH'

        # Request context for a Domain. This can be used to request context for
        # either domains like "google.com" or fully qualified domain names like
        # "mail.google.com". See the `QueryDomainRequest` and `QueryReply`
        # messages in `enrichment_service.proto` for the structure of the request and
        # response.
        rpc :QueryDomain, ::Talos::ENRICH::QueryDomainRequest, ::Talos::ENRICH::QueryReply
        # Request context for an IP, either v4 or v6. For example, the IP address
        # could either be the address a website resolves to or the source of an
        # SMTP connection. See the `QueryIPRequest` and `QueryReply` messages in
        # `enrichment_service.proto` for the structure of the request and response.
        rpc :QueryIP, ::Talos::ENRICH::QueryIPRequest, ::Talos::ENRICH::QueryReply
        # Request context for an URL such as you'd observe in a browser. See the
        # `QueryURLRequest` and `QueryReply` messages in `enrichment_service.proto` for the
        # structure of the request and response.
        rpc :QueryURL, ::Talos::ENRICH::QueryURLRequest, ::Talos::ENRICH::QueryReply
        # Request context for a SHA. The SHA is a fingerprint of a file that would
        # appear on a computer it has been downloaded onto. See the
        # `QuerySHARequest` and `QueryReply` messages in `enrichment_service.proto` for the
        # structure of the request and response.
        rpc :QuerySHA, ::Talos::ENRICH::QuerySHARequest, ::Talos::ENRICH::QueryReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
