# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-tmi-internal.proto for package 'Talos.Internal.Service'
# Original file comments:
#
# Service definition for Tag Management Interface
#

require 'grpc'
require 'service-tmi-internal_pb'

module Talos
  module Internal
    module Service
      module TMI
        #
        # Tag Management Interface
        #
        # The Tag Management Interface is the management interface for the
        # Enrichment Service. It is designed to allow data sources (like Snitcher,
        # RepTool and Feeds) to maintain the current status of the data within
        # Enrichment Service and to provide hooks for support tools (Analyst Console
        # and Sherlock)to identify and update content as escalation teams need.
        #
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'Talos.Internal.Service.TMI'

          rpc :Read, ::Talos::Internal::TMI::ReadRequest, ::Talos::Internal::TMI::ReadReply
          rpc :UpdateByContext, ::Talos::Internal::TMI::UpdateRequest, ::Talos::Internal::TMI::UpdateReply
          rpc :UpdateByMnemonic, ::Talos::Internal::TMI::MnemonicUpdateRequest, ::Talos::Internal::TMI::UpdateReply
          rpc :Lookup, ::Talos::Internal::TMI::LookupRequest, ::Talos::Internal::TMI::LookupReply
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
