# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-guid.proto for package 'Talos.Service'
# Original file comments:
#
# Service definition for GUID generation
#

require 'grpc'
require 'service-guid_pb'

module Talos
  module Service
    module GUID
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.GUID'

        # Generate a GUID for use as context IDs.
        rpc :GenGUID, ::Talos::GUID::Request, ::Talos::GUID::Reply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
