# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-tess.proto for package 'Talos.Service'
# Original file comments:
# All comments in / *** *** / will be removed upon before distribution 
#

require 'grpc'
require 'service-tess_pb'

module Talos
  module Service
    module TESS
      #
      # TESS provides Talos Email Sender Statistics
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.TESS'

        # Whois information
        # Returns: Whois information corresponding to search string such
        # as IP address, domain, or TLD
        rpc :WhoisQuery, ::Talos::TESS::WhoisSearchRequest, ::Talos::TESS::WhoisSearchResponse
        # Detail Hostname Lookup
        # Returns: hostname, organization, domain, daily/monthly magnitude.
        #
        # **
        # Replacement for /api/v2/details/host/
        # Code: sb-api/src/python/sb_org/handlers/lookup.py#get_host_details
        # Returns: dictionary:
        # {
        # hostname, organization, domain, ips: boolean,
        # category*: {description, long_description} or None,
        # daily_mag*, monthly_mag*, daychange*, web_score_name*, web_score*
        # }
        # or None
        # *
        rpc :HostDetail, ::Talos::TESS::HostDetailRequest, ::Talos::TESS::HostDetailResponse
        # Location detail lookup
        # Returns: country_code, country, city, monthly_magnitude.
        #
        # **
        # Replacement for /api/v2/location/domain/ sb-api/src/python/sb_org/db/sb_lookup.py#get_locations_by_range
        # :return: list of dictionaries:
        # [{ip: string, lastmonth, country_code, country, city, latitude, longitude}, ...]
        # *
        rpc :LocationDetail, ::Talos::TESS::LocationDetailRequest, ::Talos::TESS::LocationDetailResponse
        # Historical Volume Lookup
        # Returns: Last 30 days of volume.
        #
        #
        # Replacement for /api/v2/volume/(ip|hostname|domain|org)/
        # Code: sb-api/src/python/sb_api/view/utils/volumes.py#get_volumes
        # Returns: a dictionary with 'data' key containing a list of dictionaries:
        # {
        # 'date': <date of the day (or first day of the month) as string>,
        # 'spam': <(sampled) number of spam messages as float>,
        # 'spam_change': <change in spam volume in comparisons
        # with the previous day (month), -100..100, float>,
        # 'spam_percentage': <percentage of spam messages relatively
        # to all emails, 0..100, float>,
        # }
        rpc :VolumeInfoHistorical30Days, ::Talos::TESS::VolumeInfoRequest, ::Talos::TESS::VolumeInfoResponse
        # Maxmind: Domains in Organization
        # Returns: list of domains associated with an organization.
        #
        #
        # Replacement for /api/v2/domains_in_org/ sb-api/src/python/sb_org/handlers/lookup.py#get_orgs_in_domain
        # :return: dictionary:
        # {first, num, limit, count, data: [{name, lastmonth}, ...]}
        rpc :DomainsInOrg, ::Talos::TESS::DomainsInOrgRequest, ::Talos::TESS::DomainsInOrgResponse
        # Maxmind: Organizations in Domain
        # Returns: list of organizations associated with a domain.
        #
        #
        # Replacement for /api/v2/orgs_in_domain/  sb-api/src/python/sb_org/handlers/lookup#get_domains_in_org
        # :return: dictionary:
        # {first, num, limit, count, data: [{name, lastmonth}, ...]}
        rpc :OrgsInDomain, ::Talos::TESS::OrgsInDomainRequest, ::Talos::TESS::OrgsInDomainResponse
        # Top Senders by Country
        # Returns: Top senders information for the given country and duration.
        #
        # **
        # Replacement for /api/v2/top_stats/country/
        # Code: sb-api/src/python/sb_org/handlers/top_stats.py#get_country_top_senders
        # Returns: dictionary:
        # {
        # timestamp,
        # center: {latitude, longitude, zoom} or None
        # data: [{ip, ip_int, hostname, volume, volume_change,
        # organization, latitude, longitude, reputation}, ...]
        # }
        # *
        rpc :TopSendersByCountry, ::Talos::TESS::TopSendersByCountryRequest, ::Talos::TESS::TopSendersByCountryResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
