# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-connection-status.proto for package 'Talos.Service'
# Original file comments:
#
# Service definition for Connection status
#

require 'grpc'
require 'service-connection-status_pb'

module Talos
  module Service
    module ConnectionStatus
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.ConnectionStatus'

        # Request a Connection Status message.
        rpc :ConnectionStatus, ::Talos::ConnectionStatus::Request, ::Talos::ConnectionStatus::Reply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
