# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-tess-internal.proto for package 'Talos.Internal.Service'

require 'grpc'
require 'service-tess-internal_pb'

module Talos
  module Internal
    module Service
      module TESS
        #
        # TESS provides Talos Email Sender Statistics
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'Talos.Internal.Service.TESS'

          # Country threat volume per country code
          # Returns: Country threat volumne corresponding to country code
          rpc :CountryThreatVolume, ::Talos::Internal::TESS::CountryThreatVolumeRequest, ::Talos::Internal::TESS::CountryThreatVolumeResponse
          # Daily Email Volume
          # Returns: Daily Email Volume
          rpc :DailyEmailVolume, ::Talos::Internal::TESS::DailyEmailVolumeRequest, ::Talos::Internal::TESS::DailyEmailVolumeResponse
          # Maxmind: Domains in Organization
          # Returns: list of domains associated with an organization.
          rpc :DomainsInOrg, ::Talos::Internal::TESS::DomainsInOrgRequest, ::Talos::Internal::TESS::DomainsInOrgResponse
          # Detail Hostname Lookup
          # Returns: hostname, organization, domain, daily/monthly magnitude.
          rpc :HostDetail, ::Talos::Internal::TESS::HostDetailRequest, ::Talos::Internal::TESS::HostDetailResponse
          # Location detail lookup
          # Returns: country_code, country, city, monthly_magnitude.
          rpc :LocationDetail, ::Talos::Internal::TESS::LocationDetailRequest, ::Talos::Internal::TESS::LocationDetailResponse
          # Organizations in Domain
          # Returns: list of organizations associated with a domain.
          rpc :OrgsInDomain, ::Talos::Internal::TESS::OrgsInDomainRequest, ::Talos::Internal::TESS::OrgsInDomainResponse
          # Threat Volume per day or month
          # Returns: Threat volume per day or month
          rpc :ThreatVolumes, ::Talos::Internal::TESS::ThreatVolumesRequest, ::Talos::Internal::TESS::ThreatVolumesResponse
          # Threat Volume per Country
          # Returns: Volume per country request
          rpc :ThreatVolumesPerCountry, ::Talos::Internal::TESS::ThreatVolumesPerCountryRequest, ::Talos::Internal::TESS::ThreatVolumesPerCountryResponse
          # Top Senders by Country
          # Returns: Top senders information for the given country and duration.
          rpc :TopSendersByCountry, ::Talos::Internal::TESS::TopSendersByCountryRequest, ::Talos::Internal::TESS::TopSendersByCountryResponse
          # Top Senders Location by source
          # Returns: Top senders location by source
          rpc :TopSendersLocations, ::Talos::Internal::TESS::TopSendersLocationsRequest, ::Talos::Internal::TESS::TopSendersLocationsResponse
          # Top Senders List
          # Returns: Top Senders List
          rpc :TopSendersList, ::Talos::Internal::TESS::TopSendersListRequest, ::Talos::Internal::TESS::TopSendersListResponse
          # Historical Volume Lookup
          # Returns: Last 30 days of volume.
          rpc :VolumeInfoHistorical30Days, ::Talos::Internal::TESS::VolumeInfoRequest, ::Talos::Internal::TESS::VolumeInfoResponse
          # Related IPs Lookup
          # Returns: Related IP hostname and volume.
          rpc :RelatedIPs, ::Talos::Internal::TESS::RelatedIPsRequest, ::Talos::Internal::TESS::RelatedIPsResponse
          # Whois information
          # Returns: Whois information corresponding to search string such
          # as IP address, domain, or TLD
          rpc :WhoisQuery, ::Talos::Internal::TESS::WhoisSearchRequest, ::Talos::Internal::TESS::WhoisSearchResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
