# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-urs.proto

require 'google/protobuf'

require 'talos_pb'
require 'urs_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service-urs.proto", :syntax => :proto3) do
  end
end

module Talos
  module Service
  end
end
