# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service-sdr.proto for package 'Talos.Service'
# Original file comments:
#
# Service definition for Sender Domain Reputation
#

require 'grpc'
require 'service-sdr_pb'

module Talos
  module Service
    module SDR
      #
      # Sender Domain Reputation
      #
      # Provides mechanisms for determining the safety and reputation of an email
      # sender. Two query methods are supported, the EnvelopeQuery and DataQuery.
      # EnvelopeQuery is to be called first at the end of the envelope phase of the
      # connection. DataQuery is to be called once all available mail data is
      # received. The result returned will contain a composite reputation for all
      # hosts in the call, with the threat level indicating the resulting verdict.
      # Further, ServiceData is sent along with each reply that will be crucial to
      # pass on to CASE for additional processing.
      #
      # If an EnvelopeQuery is not made (i.e. DataQuery is the sole query), the
      # envelope (SMTP + DNS response) data MUST be presented to the DataQuery RPC.
      #
      # The target workflow with respect to this service is:
      #
      # Appliance     <--> Talos Cloud Service
      # ---
      # EnvelopeQuery --->
      #               <---  EnvelopeReply
      # DataQuery     --->
      #               <---  DataReply
      #
      # Calls to retrieve the ThreatLevelMap and ThreatCatMap must be made as
      # discussed in the service definitions for `QueryThreatCatMap` and 
      # `QueryThreatLevelMap`.
      #
      # New integrations are advised to review several available resources and
      # reach out to the Talos Integrations team for proper guidance.
      # Resources include the Protobuf specifications herein, RFC5321 covering the
      # SMTP protocol which this service is centered around, and the data usage
      # guide.
      #
      # Refer to the
      # [Talos Intelligence Usage Guidance](https://wiki.cisco.com/x/P3vGH)
      # for how to use and display data in responses.
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Talos.Service.SDR'

        # Request a reputation verdict based on sender information in the SMTP
        # envelope.
        # See the `EnvelopeQuery` and `EnvelopeReply` messages in `sdr.proto`
        # for the structure of the request and response.
        rpc :EnvelopeQuery, ::Talos::SDR::EnvelopeRequest, ::Talos::SDR::EnvelopeReply
        # This RPC endpoint is not yet implemented.
        # Bidirectional streaming requests reputation verdicts based on sender
        # information in the SMTP envelope.
        rpc :BidiEnvelopeQuery, stream(::Talos::SDR::EnvelopeRequest), stream(::Talos::SDR::EnvelopeReply)
        # Request a reputation verdict based on sending domains.
        # See the `DataQuery` and `DataReply` messages in `sdr.proto`
        # for the structure of the request and response.
        rpc :DataQuery, ::Talos::SDR::DataRequest, ::Talos::SDR::DataReply
        # This RPC endpoint is not yet implemented.
        # Bidirectional streaming requests for Sending-Domain reputation data.
        rpc :BidiDataQuery, stream(::Talos::SDR::DataRequest), stream(::Talos::SDR::DataReply)
        # Deprecated. Please use DataQuery() instead.
        rpc :Query, ::Talos::SDR::Request, ::Talos::SDR::Reply
        # Request a mapping of threat category ID to mnemonic and description.
        # This should be called whenever `threat_cat_map_version` in a response
        # from an `EnvelopeQuery` or `DataQuery` service method call is
        # larger than the version of the Threat Category Map that you have
        # cached. For details on the structure of the Threat Category Map, see
        # the `ThreatCategoryMap` message in `talos.proto`.
        rpc :QueryThreatCatMap, ::Talos::SDR::ThreatCatMapRequest, ::Talos::ThreatCategoryMap
        # Request a mapping of threat level ID to mnemonic and description.
        # This should be called whenever `threat_level_map_version` in a response
        # from an `EnvelopeQuery` or `DataQuery` service method call is
        # larger than the version of the Threat Level Map that you have
        # cached. For details on the structure of the Threat Level Map, see
        # the `ThreatLevelMap` message in `talos.proto`.
        rpc :QueryThreatLevelMap, ::Talos::SDR::ThreatLevelMapRequest, ::Talos::ThreatLevelMap
      end

      Stub = Service.rpc_stub_class
    end
  end
end
