# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tess.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tess.proto", :syntax => :proto3) do
    add_message "Talos.TESS.WhoisSearchRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :search_string, :string, 2
    end
    add_message "Talos.TESS.WhoisSearchResponse" do
      optional :result, :string, 1
      optional :status, :enum, 2, "Talos.TESS.WhoisSearchResponse.WhoisStatus"
      optional :status_message, :string, 3
    end
    add_enum "Talos.TESS.WhoisSearchResponse.WhoisStatus" do
      value :WHOIS_SUCCESS, 0
      value :WHOIS_WARNING, 1
      value :WHOIS_ERROR, 2
    end
    add_message "Talos.TESS.OrgInfo" do
      optional :org_name, :string, 1
    end
    add_message "Talos.TESS.DomainInfo" do
      optional :domain_name, :string, 1
    end
    add_message "Talos.TESS.LocationDetailRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      oneof :info do
        optional :host_info, :message, 3, "Talos.TESS.HostInfo"
        optional :domain_info, :message, 4, "Talos.TESS.DomainInfo"
        optional :org_info, :message, 5, "Talos.TESS.OrgInfo"
      end
    end
    add_message "Talos.TESS.LocationInfo" do
      optional :geo_location, :message, 1, "Talos.GeoLocation"
      optional :monthly_magnitude_x10, :uint32, 2
    end
    add_message "Talos.TESS.LocationDetailResponse" do
      repeated :location_info, :message, 2, "Talos.TESS.LocationInfo"
    end
    add_message "Talos.TESS.MagnitudeInfo" do
      optional :daily_x10, :uint32, 1
      optional :monthly_x10, :uint32, 2
    end
    add_message "Talos.TESS.Address" do
      oneof :address do
        optional :ipv4_addr, :fixed32, 1
        optional :ipv6_addr, :bytes, 2
      end
    end
    add_message "Talos.TESS.HostInfo" do
      optional :hostname, :string, 1
    end
    add_message "Talos.TESS.HostDetailRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :host_info, :message, 2, "Talos.TESS.HostInfo"
    end
    add_message "Talos.TESS.HostDetailResponse" do
      optional :host_info, :message, 1, "Talos.TESS.HostInfo"
      optional :org_info, :message, 2, "Talos.TESS.OrgInfo"
      optional :domain_info, :message, 3, "Talos.TESS.DomainInfo"
      optional :host_magnitude, :message, 4, "Talos.TESS.MagnitudeInfo"
    end
    add_message "Talos.TESS.VolumeInfoRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      oneof :info do
        optional :address, :message, 2, "Talos.TESS.Address"
        optional :host_info, :message, 3, "Talos.TESS.HostInfo"
        optional :domain_info, :message, 4, "Talos.TESS.DomainInfo"
        optional :org_info, :message, 5, "Talos.TESS.OrgInfo"
      end
    end
    add_message "Talos.TESS.VolumeInfo" do
      optional :timestamp, :uint64, 1
      optional :daily_x10, :uint32, 2
    end
    add_message "Talos.TESS.VolumeInfoResponse" do
      repeated :volume_info, :message, 1, "Talos.TESS.VolumeInfo"
    end
    add_message "Talos.TESS.DomainMagnitude" do
      optional :domain_info, :message, 1, "Talos.TESS.DomainInfo"
      optional :magnitude, :message, 2, "Talos.TESS.MagnitudeInfo"
    end
    add_message "Talos.TESS.DomainsInOrgRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :org_info, :message, 2, "Talos.TESS.OrgInfo"
    end
    add_message "Talos.TESS.DomainsInOrgResponse" do
      repeated :domain_magnitude, :message, 1, "Talos.TESS.DomainMagnitude"
    end
    add_message "Talos.TESS.OrgMagnitude" do
      optional :org_info, :message, 1, "Talos.TESS.OrgInfo"
      optional :magnitude, :message, 2, "Talos.TESS.MagnitudeInfo"
    end
    add_message "Talos.TESS.OrgsInDomainRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :domain_info, :message, 2, "Talos.TESS.DomainInfo"
    end
    add_message "Talos.TESS.OrgsInDomainResponse" do
      repeated :org_magnitude, :message, 1, "Talos.TESS.OrgMagnitude"
    end
    add_message "Talos.TESS.TopSendersData" do
      optional :address, :message, 1, "Talos.TESS.Address"
      optional :host_info, :message, 2, "Talos.TESS.HostInfo"
      optional :volume_x10, :uint32, 3
      optional :volume_change_x10, :int32, 4
      optional :org_info, :message, 5, "Talos.TESS.OrgInfo"
      optional :geo_coords, :message, 6, "Talos.GeoCoords"
    end
    add_message "Talos.TESS.TopSendersByCountryRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :country_code, :string, 2
      optional :duration, :enum, 3, "Talos.TESS.TopSendersByCountryRequest.Duration"
    end
    add_enum "Talos.TESS.TopSendersByCountryRequest.Duration" do
      value :LAST_DAY, 0
      value :LAST_MONTH, 1
    end
    add_message "Talos.TESS.TopSendersByCountryResponse" do
      optional :timestamp, :uint64, 1
      repeated :data, :message, 2, "Talos.TESS.TopSendersData"
    end
  end
end

module Talos
  module TESS
    WhoisSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.WhoisSearchRequest").msgclass
    WhoisSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.WhoisSearchResponse").msgclass
    WhoisSearchResponse::WhoisStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.WhoisSearchResponse.WhoisStatus").enummodule
    OrgInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.OrgInfo").msgclass
    DomainInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.DomainInfo").msgclass
    LocationDetailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.LocationDetailRequest").msgclass
    LocationInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.LocationInfo").msgclass
    LocationDetailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.LocationDetailResponse").msgclass
    MagnitudeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.MagnitudeInfo").msgclass
    Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.Address").msgclass
    HostInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.HostInfo").msgclass
    HostDetailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.HostDetailRequest").msgclass
    HostDetailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.HostDetailResponse").msgclass
    VolumeInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.VolumeInfoRequest").msgclass
    VolumeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.VolumeInfo").msgclass
    VolumeInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.VolumeInfoResponse").msgclass
    DomainMagnitude = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.DomainMagnitude").msgclass
    DomainsInOrgRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.DomainsInOrgRequest").msgclass
    DomainsInOrgResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.DomainsInOrgResponse").msgclass
    OrgMagnitude = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.OrgMagnitude").msgclass
    OrgsInDomainRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.OrgsInDomainRequest").msgclass
    OrgsInDomainResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.OrgsInDomainResponse").msgclass
    TopSendersData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.TopSendersData").msgclass
    TopSendersByCountryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.TopSendersByCountryRequest").msgclass
    TopSendersByCountryRequest::Duration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.TopSendersByCountryRequest.Duration").enummodule
    TopSendersByCountryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TESS.TopSendersByCountryResponse").msgclass
  end
end
