# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tess-internal.proto

require 'google/protobuf'

require 'talos_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tess-internal.proto", :syntax => :proto3) do
    add_message "Talos.Internal.TESS.WhoisSearchRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :search_string, :string, 2
    end
    add_message "Talos.Internal.TESS.WhoisSearchResponse" do
      optional :result, :string, 1
      optional :status, :enum, 2, "Talos.Internal.TESS.WhoisSearchResponse.WhoisStatus"
      optional :status_message, :string, 3
    end
    add_enum "Talos.Internal.TESS.WhoisSearchResponse.WhoisStatus" do
      value :WHOIS_SUCCESS, 0
      value :WHOIS_WARNING, 1
      value :WHOIS_ERROR, 2
    end
    add_message "Talos.Internal.TESS.CountryInfo" do
      optional :code, :string, 1
      optional :name, :string, 2
    end
    add_message "Talos.Internal.TESS.OrgInfo" do
      optional :org_name, :string, 1
    end
    add_message "Talos.Internal.TESS.DomainInfo" do
      optional :domain_name, :string, 1
    end
    add_message "Talos.Internal.TESS.LocationInfo" do
      optional :geo_location, :message, 1, "Talos.GeoLocation"
      optional :monthly_magnitude_x10, :uint32, 2
    end
    add_message "Talos.Internal.TESS.LocationDetailRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      oneof :info do
        optional :ip, :message, 2, "Talos.IPAddress"
        optional :host_info, :message, 3, "Talos.Internal.TESS.HostInfo"
        optional :domain_info, :message, 4, "Talos.Internal.TESS.DomainInfo"
        optional :org_info, :message, 5, "Talos.Internal.TESS.OrgInfo"
      end
    end
    add_message "Talos.Internal.TESS.LocationDetailResponse" do
      repeated :location_info, :message, 1, "Talos.Internal.TESS.LocationInfo"
    end
    add_message "Talos.Internal.TESS.MagnitudeInfo" do
      optional :daily_x10, :uint32, 1
      optional :monthly_x10, :uint32, 2
    end
    add_message "Talos.Internal.TESS.HostInfo" do
      optional :hostname, :string, 1
    end
    add_message "Talos.Internal.TESS.HostDetailRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :host_info, :message, 2, "Talos.Internal.TESS.HostInfo"
    end
    add_message "Talos.Internal.TESS.HostDetailResponse" do
      optional :host_info, :message, 1, "Talos.Internal.TESS.HostInfo"
      optional :org_info, :message, 2, "Talos.Internal.TESS.OrgInfo"
      optional :domain_info, :message, 3, "Talos.Internal.TESS.DomainInfo"
      optional :host_magnitude, :message, 4, "Talos.Internal.TESS.MagnitudeInfo"
      optional :day_magnitude_change_percentage_x100, :int32, 5
    end
    add_message "Talos.Internal.TESS.VolumeInfoRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      oneof :info do
        optional :ip, :message, 2, "Talos.IPAddress"
        optional :host_info, :message, 3, "Talos.Internal.TESS.HostInfo"
        optional :domain_info, :message, 4, "Talos.Internal.TESS.DomainInfo"
        optional :org_info, :message, 5, "Talos.Internal.TESS.OrgInfo"
      end
    end
    add_message "Talos.Internal.TESS.VolumeInfo" do
      optional :timestamp, :uint64, 1
      optional :daily_x10, :uint32, 2
    end
    add_message "Talos.Internal.TESS.VolumeInfoResponse" do
      repeated :volume_info, :message, 1, "Talos.Internal.TESS.VolumeInfo"
      optional :monthly_x10, :uint32, 2
      optional :host_info, :message, 3, "Talos.Internal.TESS.HostInfo"
    end
    add_message "Talos.Internal.TESS.DomainMagnitude" do
      optional :domain_info, :message, 1, "Talos.Internal.TESS.DomainInfo"
      optional :magnitude, :message, 2, "Talos.Internal.TESS.MagnitudeInfo"
    end
    add_message "Talos.Internal.TESS.DomainsInOrgRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :org_info, :message, 2, "Talos.Internal.TESS.OrgInfo"
    end
    add_message "Talos.Internal.TESS.DomainsInOrgResponse" do
      repeated :domain_magnitude, :message, 1, "Talos.Internal.TESS.DomainMagnitude"
    end
    add_message "Talos.Internal.TESS.OrgMagnitude" do
      optional :org_info, :message, 1, "Talos.Internal.TESS.OrgInfo"
      optional :magnitude, :message, 2, "Talos.Internal.TESS.MagnitudeInfo"
    end
    add_message "Talos.Internal.TESS.OrgsInDomainRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :domain_info, :message, 2, "Talos.Internal.TESS.DomainInfo"
    end
    add_message "Talos.Internal.TESS.OrgsInDomainResponse" do
      repeated :org_magnitude, :message, 1, "Talos.Internal.TESS.OrgMagnitude"
    end
    add_message "Talos.Internal.TESS.TopEmailSender" do
      optional :ip, :message, 1, "Talos.IPAddress"
      optional :hostname, :message, 2, "Talos.Internal.TESS.HostInfo"
      optional :day_magnitude_x10, :uint32, 3
      optional :day_magnitude_change_percentage_x100, :int32, 4
      optional :org_info, :message, 5, "Talos.Internal.TESS.OrgInfo"
      optional :geo_coords, :message, 6, "Talos.GeoCoords"
      optional :country_info, :message, 7, "Talos.Internal.TESS.CountryInfo"
    end
    add_message "Talos.Internal.TESS.TopOrgSender" do
      optional :organization, :string, 1
      optional :day_magnitude_x10, :uint32, 2
      optional :day_magnitude_change_percentage_x100, :int32, 3
      optional :domain_count, :uint32, 4
    end
    add_message "Talos.Internal.TESS.TopCountrySender" do
      optional :country_info, :message, 1, "Talos.Internal.TESS.CountryInfo"
      optional :day_magnitude_x10, :uint32, 2
      optional :day_magnitude_change_percentage_x100, :int32, 3
    end
    add_message "Talos.Internal.TESS.TopSendersListRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.Internal.TESS.TopSendersListResponse" do
      repeated :spam, :message, 1, "Talos.Internal.TESS.TopEmailSender"
      repeated :ham, :message, 2, "Talos.Internal.TESS.TopEmailSender"
      repeated :spam_org, :message, 3, "Talos.Internal.TESS.TopOrgSender"
      repeated :ham_org, :message, 4, "Talos.Internal.TESS.TopOrgSender"
      repeated :spam_country, :message, 5, "Talos.Internal.TESS.TopCountrySender"
      repeated :ham_country, :message, 6, "Talos.Internal.TESS.TopCountrySender"
    end
    add_message "Talos.Internal.TESS.TopSendersData" do
      optional :ip, :message, 1, "Talos.IPAddress"
      optional :host_info, :message, 2, "Talos.Internal.TESS.HostInfo"
      optional :volume_x10, :uint32, 3
      optional :volume_change_x10, :int32, 4
      optional :org_info, :message, 5, "Talos.Internal.TESS.OrgInfo"
      optional :geo_coords, :message, 6, "Talos.GeoCoords"
    end
    add_message "Talos.Internal.TESS.TopSendersByCountryRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :country_code, :string, 2
      optional :duration, :enum, 3, "Talos.Internal.TESS.TopSendersByCountryRequest.Duration"
    end
    add_enum "Talos.Internal.TESS.TopSendersByCountryRequest.Duration" do
      value :LAST_DAY, 0
      value :LAST_MONTH, 1
    end
    add_message "Talos.Internal.TESS.TopSendersByCountryResponse" do
      optional :timestamp, :uint64, 1
      repeated :data, :message, 2, "Talos.Internal.TESS.TopSendersData"
    end
    add_message "Talos.Internal.TESS.ThreatVolume" do
      optional :timestamp, :uint64, 1
      optional :spam_volume, :int32, 2
      optional :spam_volume_percentage_x100, :uint32, 3
      optional :spam_volume_change_percentage_x100, :int32, 4
    end
    add_message "Talos.Internal.TESS.ThreatVolumesRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :unit, :enum, 2, "Talos.Internal.TESS.ThreatVolumesRequest.Unit"
    end
    add_enum "Talos.Internal.TESS.ThreatVolumesRequest.Unit" do
      value :PER_DAY, 0
      value :PER_MONTH, 1
    end
    add_message "Talos.Internal.TESS.ThreatVolumesResponse" do
      repeated :details, :message, 1, "Talos.Internal.TESS.ThreatVolume"
    end
    add_message "Talos.Internal.TESS.ThreatVolumesPerCountryRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :country_code, :string, 2
    end
    add_message "Talos.Internal.TESS.ThreatVolumesPerCountryResponse" do
      repeated :data, :message, 1, "Talos.Internal.TESS.ThreatVolumesPerCountryData"
    end
    add_message "Talos.Internal.TESS.ThreatVolumesPerCountryData" do
      optional :timestamp, :uint64, 1
      optional :spam_magnitude_x10, :uint32, 2
      optional :ham_magnitude_x10, :uint32, 3
    end
    add_message "Talos.Internal.TESS.TopSendersLocationsRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :source, :string, 2
    end
    add_message "Talos.Internal.TESS.TopSendersLocationsResponse" do
      optional :timestamp, :uint64, 1
      repeated :locations, :message, 2, "Talos.Internal.TESS.SenderLocation"
    end
    add_message "Talos.Internal.TESS.SenderLocation" do
      optional :geo_coords, :message, 1, "Talos.GeoCoords"
      repeated :ips, :message, 2, "Talos.Internal.TESS.SenderIPInfo"
    end
    add_message "Talos.Internal.TESS.SenderIPInfo" do
      optional :ip, :message, 1, "Talos.IPAddress"
      optional :host_info, :message, 2, "Talos.Internal.TESS.HostInfo"
      optional :day_magnitude_x10, :uint32, 3
    end
    add_message "Talos.Internal.TESS.CountryThreatVolumeRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :country_code, :string, 2
    end
    add_message "Talos.Internal.TESS.CountryThreatVolumeResponse" do
      optional :country_info, :message, 1, "Talos.Internal.TESS.CountryInfo"
      optional :email_magnitude, :message, 2, "Talos.Internal.TESS.MagnitudeInfo"
      optional :email_day_volume_percentage_x100, :int32, 3
      optional :spam_magnitude, :message, 4, "Talos.Internal.TESS.MagnitudeInfo"
      optional :spam_day_volume_percentage_x100, :int32, 5
    end
    add_message "Talos.Internal.TESS.DailyEmailVolumeRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
    end
    add_message "Talos.Internal.TESS.DailyEmailVolumeResponse" do
      optional :timestamp, :uint64, 1
      optional :spam_percentage_x100, :uint32, 2
      optional :ham_percentage_x100, :uint32, 3
      optional :virus_percentage_x100, :uint32, 4
      optional :spam_volume_x10000, :uint64, 5
      optional :ham_volume_x10000, :uint64, 6
      optional :virus_volume_x10000, :uint64, 7
      optional :total_volume_x10000, :uint64, 8
    end
    add_message "Talos.Internal.TESS.RelatedIPsRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      oneof :info do
        optional :ip, :message, 2, "Talos.IPAddress"
        optional :cidr, :string, 3
        optional :host_info, :message, 4, "Talos.Internal.TESS.HostInfo"
        optional :domain_info, :message, 5, "Talos.Internal.TESS.DomainInfo"
        optional :org_info, :message, 6, "Talos.Internal.TESS.OrgInfo"
      end
    end
    add_message "Talos.Internal.TESS.RelatedIPsInfo" do
      optional :ip, :message, 1, "Talos.IPAddress"
      optional :host_info, :message, 2, "Talos.Internal.TESS.HostInfo"
      optional :magnitude, :message, 3, "Talos.Internal.TESS.MagnitudeInfo"
    end
    add_message "Talos.Internal.TESS.RelatedIPsResponse" do
      repeated :data, :message, 1, "Talos.Internal.TESS.RelatedIPsInfo"
    end
  end
end

module Talos
  module Internal
    module TESS
      WhoisSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.WhoisSearchRequest").msgclass
      WhoisSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.WhoisSearchResponse").msgclass
      WhoisSearchResponse::WhoisStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.WhoisSearchResponse.WhoisStatus").enummodule
      CountryInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.CountryInfo").msgclass
      OrgInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.OrgInfo").msgclass
      DomainInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.DomainInfo").msgclass
      LocationInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.LocationInfo").msgclass
      LocationDetailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.LocationDetailRequest").msgclass
      LocationDetailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.LocationDetailResponse").msgclass
      MagnitudeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.MagnitudeInfo").msgclass
      HostInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.HostInfo").msgclass
      HostDetailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.HostDetailRequest").msgclass
      HostDetailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.HostDetailResponse").msgclass
      VolumeInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.VolumeInfoRequest").msgclass
      VolumeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.VolumeInfo").msgclass
      VolumeInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.VolumeInfoResponse").msgclass
      DomainMagnitude = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.DomainMagnitude").msgclass
      DomainsInOrgRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.DomainsInOrgRequest").msgclass
      DomainsInOrgResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.DomainsInOrgResponse").msgclass
      OrgMagnitude = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.OrgMagnitude").msgclass
      OrgsInDomainRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.OrgsInDomainRequest").msgclass
      OrgsInDomainResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.OrgsInDomainResponse").msgclass
      TopEmailSender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopEmailSender").msgclass
      TopOrgSender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopOrgSender").msgclass
      TopCountrySender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopCountrySender").msgclass
      TopSendersListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersListRequest").msgclass
      TopSendersListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersListResponse").msgclass
      TopSendersData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersData").msgclass
      TopSendersByCountryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersByCountryRequest").msgclass
      TopSendersByCountryRequest::Duration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersByCountryRequest.Duration").enummodule
      TopSendersByCountryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersByCountryResponse").msgclass
      ThreatVolume = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolume").msgclass
      ThreatVolumesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolumesRequest").msgclass
      ThreatVolumesRequest::Unit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolumesRequest.Unit").enummodule
      ThreatVolumesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolumesResponse").msgclass
      ThreatVolumesPerCountryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolumesPerCountryRequest").msgclass
      ThreatVolumesPerCountryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolumesPerCountryResponse").msgclass
      ThreatVolumesPerCountryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.ThreatVolumesPerCountryData").msgclass
      TopSendersLocationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersLocationsRequest").msgclass
      TopSendersLocationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.TopSendersLocationsResponse").msgclass
      SenderLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.SenderLocation").msgclass
      SenderIPInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.SenderIPInfo").msgclass
      CountryThreatVolumeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.CountryThreatVolumeRequest").msgclass
      CountryThreatVolumeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.CountryThreatVolumeResponse").msgclass
      DailyEmailVolumeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.DailyEmailVolumeRequest").msgclass
      DailyEmailVolumeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.DailyEmailVolumeResponse").msgclass
      RelatedIPsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.RelatedIPsRequest").msgclass
      RelatedIPsInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.RelatedIPsInfo").msgclass
      RelatedIPsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TESS.RelatedIPsResponse").msgclass
    end
  end
end
