# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tmi-internal.proto

require 'google/protobuf'

require 'talos_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tmi-internal.proto", :syntax => :proto3) do
    add_message "Talos.Internal.TMI.Observable" do
      oneof :observed do
        optional :domain, :string, 1
        optional :url, :message, 2, "Talos.URL"
        optional :ip, :message, 3, "Talos.IPAddress"
        optional :sha, :string, 4
      end
    end
    add_message "Talos.Internal.TMI.Signature" do
      oneof :signature do
        optional :snort_rule_id, :uint32, 1
        optional :snort_rule_group_id, :uint32, 2
        optional :clam_av_sig_name, :string, 3
        optional :detection_name, :string, 4
      end
    end
    add_message "Talos.Internal.TMI.EnrichTag" do
      optional :tag, :message, 1, "Talos.ContextTag"
      repeated :reports, :message, 2, "Talos.Internal.TMI.Report"
      optional :suppressed_by, :message, 3, "Talos.Internal.TMI.Suppression"
    end
    add_message "Talos.Internal.TMI.EnrichGroup" do
      optional :reported, :message, 1, "Talos.Internal.TMI.Report"
      optional :updated_ts, :uint64, 2
      optional :group, :message, 3, "Talos.ContextGroup"
      repeated :tags, :message, 4, "Talos.Internal.TMI.EnrichTag"
      optional :suppressed_by, :message, 5, "Talos.Internal.TMI.Suppression"
    end
    add_message "Talos.Internal.TMI.Report" do
      optional :created_ts, :uint64, 1
      optional :source, :message, 2, "Talos.Internal.TMI.DataSource"
      optional :suppressed_by, :message, 3, "Talos.Internal.TMI.Suppression"
      optional :marked_for_delete, :bool, 4
      optional :raw_observable, :string, 5
    end
    add_message "Talos.Internal.TMI.SourceSuppression" do
      optional :source, :message, 1, "Talos.Internal.TMI.DataSource"
      optional :suppressed_by, :message, 2, "Talos.Internal.TMI.Suppression"
    end
    add_message "Talos.Internal.TMI.Suppression" do
      optional :source, :message, 1, "Talos.Internal.TMI.DataSource"
      optional :suppressed_ts, :uint64, 2
    end
    add_message "Talos.Internal.TMI.DataSource" do
      optional :source, :string, 1
      optional :processor, :string, 2
    end
    add_message "Talos.Internal.TMI.ReadRequest" do
      optional :observation, :message, 1, "Talos.Internal.TMI.Observable"
      optional :signature, :message, 2, "Talos.Internal.TMI.Signature"
    end
    add_message "Talos.Internal.TMI.ReadReply" do
      repeated :items, :message, 1, "Talos.Internal.TMI.ObservableItem"
    end
    add_message "Talos.Internal.TMI.ObservableItem" do
      optional :observation, :message, 1, "Talos.Internal.TMI.Observable"
      repeated :tags, :message, 2, "Talos.Internal.TMI.EnrichTag"
      repeated :groups, :message, 3, "Talos.Internal.TMI.EnrichGroup"
      optional :suppressed_by, :message, 4, "Talos.Internal.TMI.Suppression"
      repeated :suppressed_sources, :message, 5, "Talos.Internal.TMI.SourceSuppression"
      optional :signature, :message, 6, "Talos.Internal.TMI.Signature"
    end
    add_message "Talos.Internal.TMI.UpdateItem" do
      optional :observation, :message, 1, "Talos.Internal.TMI.Observable"
      optional :action, :enum, 2, "Talos.Internal.TMI.Action"
      repeated :tags, :message, 3, "Talos.ContextTag"
      repeated :groups, :message, 4, "Talos.ContextGroup"
      optional :suppress_target, :message, 5, "Talos.Internal.TMI.DataSource"
      optional :signature, :message, 6, "Talos.Internal.TMI.Signature"
    end
    add_message "Talos.Internal.TMI.UpdateRequest" do
      repeated :items, :message, 1, "Talos.Internal.TMI.UpdateItem"
    end
    add_message "Talos.Internal.TMI.MnemonicUpdateRequest" do
      repeated :items, :message, 1, "Talos.Internal.TMI.MnemonicUpdateItem"
    end
    add_message "Talos.Internal.TMI.MnemonicUpdateItem" do
      optional :observation, :message, 1, "Talos.Internal.TMI.Observable"
      optional :action, :enum, 2, "Talos.Internal.TMI.Action"
      repeated :tag_mnemonics, :string, 3
      optional :group_mnemonics, :message, 4, "Talos.Internal.TMI.MnemonicGroup"
      optional :suppress_target, :message, 5, "Talos.Internal.TMI.DataSource"
      optional :signature, :message, 6, "Talos.Internal.TMI.Signature"
    end
    add_message "Talos.Internal.TMI.MnemonicGroup" do
      optional :group_mnemonic, :string, 1
      repeated :tag_mnemonics, :string, 2
    end
    add_message "Talos.Internal.TMI.UpdateError" do
      optional :index, :int32, 1
      optional :error, :string, 2
    end
    add_message "Talos.Internal.TMI.UpdateResponse" do
      optional :item_error, :message, 1, "Talos.Internal.TMI.UpdateError"
      repeated :tag_error, :message, 2, "Talos.Internal.TMI.UpdateError"
      repeated :group_error, :message, 3, "Talos.Internal.TMI.UpdateError"
    end
    add_message "Talos.Internal.TMI.UpdateReply" do
      repeated :responses, :message, 1, "Talos.Internal.TMI.UpdateResponse"
    end
    add_message "Talos.Internal.TMI.LookupRequest" do
      repeated :mnemonics, :string, 1
    end
    add_message "Talos.Internal.TMI.TagResponse" do
      optional :tag, :message, 1, "Talos.ContextTag"
      optional :error, :enum, 2, "Talos.Internal.TMI.TagResponse.TagLookupError"
    end
    add_enum "Talos.Internal.TMI.TagResponse.TagLookupError" do
      value :ERROR_NONE, 0
      value :ERROR_NOT_FOUND, 1
    end
    add_message "Talos.Internal.TMI.LookupReply" do
      repeated :response, :message, 1, "Talos.Internal.TMI.TagResponse"
    end
    add_message "Talos.Internal.TMI.UpdateAuditLog" do
      optional :datasource, :message, 1, "Talos.Internal.TMI.DataSource"
      optional :request, :message, 2, "Talos.Internal.TMI.UpdateRequest"
      optional :reply, :message, 3, "Talos.Internal.TMI.UpdateReply"
      optional :client, :message, 4, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 5
      optional :response_sent_ts, :uint64, 6
      optional :grpc_status_code, :uint32, 7
    end
    add_enum "Talos.Internal.TMI.Action" do
      value :UPDATE_ADD, 0
      value :UPDATE_DELETE, 1
      value :UPDATE_REPLACE, 2
      value :UPDATE_SUPPRESS_REPORT, 3
      value :UPDATE_UNSUPPRESS_REPORT, 4
      value :UPDATE_SUPPRESS_TAG_GRP, 5
      value :UPDATE_UNSUPPRESS_TAG_GRP, 6
      value :UPDATE_SUPPRESS_SOURCE, 7
      value :UPDATE_UNSUPPRESS_SOURCE, 8
      value :UPDATE_SUPPRESS_OBSERVATION, 9
      value :UPDATE_UNSUPPRESS_OBSERVATION, 10
    end
  end
end

module Talos
  module Internal
    module TMI
      Observable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.Observable").msgclass
      Signature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.Signature").msgclass
      EnrichTag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.EnrichTag").msgclass
      EnrichGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.EnrichGroup").msgclass
      Report = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.Report").msgclass
      SourceSuppression = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.SourceSuppression").msgclass
      Suppression = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.Suppression").msgclass
      DataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.DataSource").msgclass
      ReadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.ReadRequest").msgclass
      ReadReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.ReadReply").msgclass
      ObservableItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.ObservableItem").msgclass
      UpdateItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.UpdateItem").msgclass
      UpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.UpdateRequest").msgclass
      MnemonicUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.MnemonicUpdateRequest").msgclass
      MnemonicUpdateItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.MnemonicUpdateItem").msgclass
      MnemonicGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.MnemonicGroup").msgclass
      UpdateError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.UpdateError").msgclass
      UpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.UpdateResponse").msgclass
      UpdateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.UpdateReply").msgclass
      LookupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.LookupRequest").msgclass
      TagResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.TagResponse").msgclass
      TagResponse::TagLookupError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.TagResponse.TagLookupError").enummodule
      LookupReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.LookupReply").msgclass
      UpdateAuditLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.UpdateAuditLog").msgclass
      Action = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.Internal.TMI.Action").enummodule
    end
  end
end
