# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tts.proto", :syntax => :proto3) do
    add_message "Talos.TTS.TaxonomyMapRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :query_key, :string, 2
      repeated :taxonomy_ids, :uint32, 3
      repeated :intelligence_type_ids, :uint32, 4
    end
  end
end

module Talos
  module TTS
    TaxonomyMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.TTS.TaxonomyMapRequest").msgclass
  end
end
