# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: urs.proto

require 'google/protobuf'

require 'talos_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("urs.proto", :syntax => :proto3) do
    add_message "Talos.URS.ReputationRequest" do
      optional :app_info, :message, 1, "Talos.AppInfo"
      optional :connection, :message, 2, "Talos.IPConnection"
      optional :msg_guid, :bytes, 3
      repeated :url, :message, 4, "Talos.URL"
      optional :do_not_resolve_dns, :bool, 5
      optional :reputation_block_threshold_x10, :sint32, 6
      optional :no_reputation_block_threshold, :bool, 7
    end
    add_message "Talos.URS.ReputationReply" do
      optional :connection_guid, :bytes, 1
      optional :msg_guid, :bytes, 2
      repeated :result, :message, 3, "Talos.URS.URLResult"
      optional :aup_cat_map_version, :uint32, 4
      optional :threat_cat_map_version, :uint32, 5
      optional :threat_level_map_version, :uint32, 6
      optional :tag_map_version, :uint32, 7
    end
    add_message "Talos.URS.PrivateReputationReply" do
      optional :reply, :message, 1, "Talos.URS.ReputationReply"
      optional :cache_hint, :string, 2
      optional :cache_ttl, :uint32, 3
    end
    add_message "Talos.URS.PrivateLog" do
      optional :request, :message, 1, "Talos.URS.ReputationRequest"
      optional :reply, :message, 2, "Talos.URS.ReputationReply"
      optional :client, :message, 3, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 4
      optional :response_sent_ts, :uint64, 5
      optional :grpc_status_code, :uint32, 6
    end
    add_message "Talos.URS.PrivateLogV2" do
      optional :request, :message, 1, "Talos.URS.ReputationRequest"
      optional :reply, :message, 2, "Talos.URS.ReputationReplyV2"
      optional :client, :message, 3, "Talos.IPEndpoint"
      optional :request_received_ts, :uint64, 4
      optional :response_sent_ts, :uint64, 5
      optional :grpc_status_code, :uint32, 6
    end
    add_message "Talos.URS.ReputationReplyV2" do
      optional :connection_guid, :bytes, 1
      optional :msg_guid, :bytes, 2
      repeated :result, :message, 3, "Talos.URS.URLVerdict"
      optional :aup_cat_map_version, :uint32, 4
      optional :threat_cat_map_version, :uint32, 5
      optional :threat_level_map_version, :uint32, 6
      optional :tag_map_version, :uint32, 7
    end
    add_message "Talos.URS.URLVerdict" do
      repeated :result, :message, 1, "Talos.URS.URLResultV2"
    end
    add_message "Talos.URS.URLResultV2" do
      optional :threat_level_id, :uint32, 1
      optional :reputation_score_x10, :sint32, 2
      optional :no_reputation_score, :bool, 3
      repeated :threat_cat_id, :uint32, 4
      repeated :aup_cat_id, :uint32, 5
      repeated :tag_id, :uint32, 6
      optional :domain_init, :int64, 7
      optional :url, :string, 9
      repeated :rep_rule_id, :uint32, 10
      optional :error, :enum, 11, "Talos.URS.URLResultV2.URLError"
      optional :error_is_temporary, :bool, 12
      optional :result_type, :enum, 13, "Talos.URS.URLResultV2.AssociatedResultType"
    end
    add_enum "Talos.URS.URLResultV2.URLError" do
      value :ERROR_NONE, 0
      value :ERROR_SHORTENER_FAIL, 1
      value :ERROR_INTERNAL, 2
      value :ERROR_INVALID_REQUEST, 3
    end
    add_enum "Talos.URS.URLResultV2.AssociatedResultType" do
      value :ASSOCIATED_RESULT_TYPE_NONE, 0
      value :ASSOCIATED_RESULT_TYPE_EP, 1
      value :ASSOCIATED_RESULT_TYPE_SHORT_URL, 2
      value :ASSOCIATED_RESULT_TYPE_RWR_URL, 3
    end
    add_message "Talos.URS.URLResult" do
      optional :threat_level_id, :uint32, 1
      optional :reputation_score_x10, :sint32, 2
      optional :no_reputation_score, :bool, 3
      repeated :threat_cat_id, :uint32, 4
      repeated :aup_cat_id, :uint32, 5
      repeated :tag_id, :uint32, 6
      optional :domain_init, :int64, 7
      optional :associated_result, :message, 8, "Talos.URS.AssociatedResults"
      optional :url, :string, 9
      repeated :rep_rule_id, :uint32, 10
      optional :error, :enum, 11, "Talos.URS.URLResult.URLError"
      optional :error_is_temporary, :bool, 12
    end
    add_enum "Talos.URS.URLResult.URLError" do
      value :ERROR_NONE, 0
      value :ERROR_SHORTENER_FAIL, 1
      value :ERROR_INTERNAL, 2
      value :ERROR_INVALID_REQUEST, 3
    end
    add_message "Talos.URS.AssociatedResults" do
      optional :result_type, :enum, 1, "Talos.URS.AssociatedResults.AssociatedResultType"
      repeated :result, :message, 2, "Talos.URS.URLResult"
    end
    add_enum "Talos.URS.AssociatedResults.AssociatedResultType" do
      value :ASSOCIATED_RESULT_TYPE_NONE, 0
      value :ASSOCIATED_RESULT_TYPE_EP, 1
      value :ASSOCIATED_RESULT_TYPE_SHORT_URL, 2
      value :ASSOCIATED_RESULT_TYPE_RWR_URL, 3
    end
    add_message "Talos.URS.AUPCatMapRequest" do
    end
    add_message "Talos.URS.ThreatCatMapRequest" do
    end
    add_message "Talos.URS.ThreatLevelMapRequest" do
    end
    add_message "Talos.URS.TagMapRequest" do
    end
  end
end

module Talos
  module URS
    ReputationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.ReputationRequest").msgclass
    ReputationReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.ReputationReply").msgclass
    PrivateReputationReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.PrivateReputationReply").msgclass
    PrivateLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.PrivateLog").msgclass
    PrivateLogV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.PrivateLogV2").msgclass
    ReputationReplyV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.ReputationReplyV2").msgclass
    URLVerdict = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.URLVerdict").msgclass
    URLResultV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.URLResultV2").msgclass
    URLResultV2::URLError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.URLResultV2.URLError").enummodule
    URLResultV2::AssociatedResultType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.URLResultV2.AssociatedResultType").enummodule
    URLResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.URLResult").msgclass
    URLResult::URLError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.URLResult.URLError").enummodule
    AssociatedResults = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.AssociatedResults").msgclass
    AssociatedResults::AssociatedResultType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.AssociatedResults.AssociatedResultType").enummodule
    AUPCatMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.AUPCatMapRequest").msgclass
    ThreatCatMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.ThreatCatMapRequest").msgclass
    ThreatLevelMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.ThreatLevelMapRequest").msgclass
    TagMapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Talos.URS.TagMapRequest").msgclass
  end
end
