# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(cvs_username:"nicherbe",committer:'true')
User.create(cvs_username:"alwillet",committer:'false')
User.create(cvs_username:"pamullen",committer:'false')


c1 = Contact.create(name: 'Giamia',about: 'Although Giamia came from a humble spark of lightning, he quickly grew to be a great craftsman, providing all the warming instruments needed by those close to him.',avatar: 'images/contacts/giamia.png')
c2 = Contact.create(name: 'Anostagia',about: 'Knowing there was a need for it, Anostagia drew on her experience and spearheaded the Flint & Flame storefront. In addition to coding the site, she also creates a few products available in the store.',avatar: 'images/contacts/anostagia.png')

p1 = Product.create(title: 'flint',price: 99,description: 'Flint is a hard, sedimentary cryptocrystalline form of the mineral quartz, categorized as a variety of chert.',isOnSale: true, image: 'images/products/flint.png',contact_id: c1.id)
p2 = Product.create(title: 'Kindling',price: 249,description: 'Easily combustible small sticks or twigs used for starting a fire.',isOnSale: false, image: 'images/products/kindling.png',contact_id: c2.id)
p3 = Product.create(title: 'Bow Drill',price: 999,description: 'The bow drill is an ancient tool. While it was usually used to make fire, it was also used for primitive woodworking and dentistry.',isOnSale: false, image: 'images/products/bow-drill.png',contact_id: c1.id)
p4 = Product.create(title: 'Tinder',price: 499,description: 'Tinder is easily combustible material used to ignite fires by rudimentary methods.',isOnSale: true, image: 'images/products/tinder.png',contact_id: c2.id)
p5 = Product.create(title: 'Birch Bark Shaving',price: 899,description: 'Fresh and easily combustable',isOnSale: true, image: 'images/products/birch.png',contact_id: c2.id)
p6 = Product.create(title: 'Matches',price:550,description:'One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface.', isOnSale: true, image:'images/products/matches.png', contact_id: c2.id)

r1 = Review.create(reviewedAt: (DateTime.now - 3.days),text: "Started a fire in no time!",rating: 4, product_id: p3.id)
r2 = Review.create(reviewedAt: DateTime.now,text: "Not the brightest flame, but warm!",rating: 3, product_id: p6.id)
r3 = Review.create(reviewedAt: (DateTime.now - 5.days),text: "This is some amazing Flint! It lasts **forever** and works even when damp! I still remember the first day when I was only a little fire sprite and got one of these in my flame stalking for treemas. My eyes lit up the moment I tried it! Here's just a few uses for it:\n\n* Create a fire using just a knife and kindling!\n* Works even after jumping in a lake (although, that's suicide for me)\n* Small enough to fit in a pocket -- if you happen to wear pants\n\n\nYears later I'm still using the _same one_. That's the biggest advantage of this -- it doesn't run out easily like matches. As long as you have something to strike it against, **you can start a fire anywhere** you have something to burn!",rating: 5, product_id: p1.id)



Reference.create(name:'telus', description:'Telus bug report information', validation: 'nil', bugzilla_format:'((FSC|TSL)\\d{8}-\\d{2})',example:'FSC20111103-05',rule_format:'<reference>',url:'https://portal.telussecuritylabs.com/threat/DATA')

Bug.create(bugzilla_id:'143429',state:'Open',summary:'Just some bug',user_id:'1',committer_id:'1',gid:'1',sid:'nil',rev:'1',notes:'These are some notes',committer_notes:'these are some committer notes')
Bug.create(bugzilla_id:'142673',state:'Pending',summary:'This is a pending bug',user_id:'2',committer_id:'1',gid:'1',sid:'nil',rev:'1',notes:'These are some more notes',committer_notes:'these are some more committer notes',reference_id:'1')


Attachment.create(bugzilla_attachment_id: '1234',filename:'some attachment',file_size:'25')


Rule.create(gid:'1',sid:'12345',rev:'1',message:'This is a message',content:'this is where the content goes',state:'open',average_check: '2.5',average_match:'1.7',tested:'false')
Rule.create(gid:'1',sid:'54321',rev:'1',message:'This is a new message',content:'content works here',state:'open',average_check: '2.2',average_match:'3.1',tested:'false')

Exploit.create(name:"exploit abc123",description:"this is an exploit that everything has",pcap_validation:"?? dont know....",data:"blah blah blah data goes here. lots of data im not sure how much data but i would imagine lots would need to be here. I could talk all day about data but i wont because there are other things to do.")



