[theme]
name = "Catppuccin Macchiato"

[colors]
AlertInfo = "#8bd5ca"
AlertWarn = "#f5a97f" # Pearch
AlertError = "#ed8796"
Annotation = "#eed49f" # Yellow
Base = "#24273a"
Guidance = "#939ab7"
Important = "#f0c6c6"
Title = "#cad3f5"
