#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'

require 'rails/all'

script_file = File.join(Rails.root, 'lib', 'kill_complaints.rb')
tmp_dir = File.join(Rails.root, 'tmp')

options = {
    :app_name   => "kill_complaints",
    :dir_mode   => :normal,
    :dir        => tmp_dir,
    :multiple   => true,
    :ontop      => false,
    :mode       => :load,
    :backtrace  => true,
    :monitor    => true,
    :log_output => true
}

Daemons.run(script_file,options)